/**
 * The words of the development tools: the panel of the playtest, the report of the tasks, the
 * debug panel. Loaded with those tools, in development only.
 */
const RU = {
  score: 'SCORE',
  practice: 'PRACTICE',
  resume: 'Продолжить',
  restart: 'Заново',
  again: 'Ещё раз',
  playtest: 'Плейтест',
  back: 'Назад',
  result: 'Итог',
  time: 'TIME',
  endless: 'Бесконечный',
  timed: '3 минуты',
  tutorial: 'Обучение',
  tune_timedSec: 'Длина режима на время, с',
  experiments: 'Эксперименты',
  expNote: 'Правила применяются со следующей партии',
  guidedStart: 'Разовые подсказки в партии',
  gentleStart: 'Первые 3 минуты без проигрыша',
  boardPreview: 'Превью грани на поле',
  matchHint: 'Подсветка шага, дающего очистку',
  floorClimb: 'С пола можно забраться на куб, который не толкается',
  dockSteps: 'Причалы — ступени: с цепочки на клетку рядом можно сойти сразу, с неё — подняться на соседний куб',
  floorLift: 'Лифт: если игрок остался на полу, следующий куб появляется под ним',
  soloOne: 'Единица у цепочки тонет одна, остальные единицы остаются',
  chainCalm: 'Цепочка от двух звеньев держит обычные кубы, пока идёт и ещё немного после',
  controls: 'Управление',
  gesture: 'Жесты',
  dpad: 'Кнопки',
  replayTutorial: 'Повторить обучение',
  stats: 'Статистика последней партии',
  copy: 'Скопировать',
  copied: 'Скопировано',
  applyRestart: 'Применить и начать заново',
  noStats: 'Партий ещё не было',
  records: 'Рекорды',
  place: '№',
  sound: 'Звук',
  motion: 'Движение',
  shake: 'Тряска',
  off: 'выкл',
  full: 'полное',
  debugPanel: 'Дебаг-панель переменных',
  debugTitle: 'Переменные',
  debugRules: 'Геймплей · со следующей партии',
  debugCamera: 'Камера · сразу',
  reset: 'Сбросить',
  close: 'Закрыть',
  tune_stepMs: 'Шаг, мс',
  tune_warnMs: 'Предупреждение, мс',
  tune_riseMs: 'Подъём куба, мс',
  tune_sinkMs: 'Утопание, мс',
  tune_spawnStartMs: 'Интервал появления на старте, мс',
  tune_spawnStepMs: 'Ускорение за уровень, мс',
  tune_spawnMinMs: 'Минимальный интервал, мс',
  tune_cubesPerLevel: 'Кубов на уровень',
  tune_startCubes: 'Стартовых кубов',
  tune_lowHeight: 'Прокат по растущему кубу: ниже высоты',
  tune_sinkLowHeight: 'Прокат по тонущему кубу: ниже высоты',
  tune_mountHeight: 'Зайти на куб с пола: ниже высоты',
  tune_stepDownHeight: 'Сойти с тонущего куба: ниже высоты',
  tune_chainLift: 'Цепочка: подъём группы при добавлении',
  tune_chainLiftMin: 'Цепочка: подъём после пяти добавлений',
  tune_feedRate: 'Доля появлений под цепочку',
  tune_helpRate: 'Доля «полезных» появлений',
  tune_targetCubes: 'Целевое число кубов на поле',
  tune_refillMs: 'Интервал при недоборе, мс',
  tune_sparseFactor: 'Интервал при целевом числе, ×',
  tune_crowdedFactor: 'Интервал на тесном поле, ×',
  tune_easyLevels: 'Уровней с лёгкими гранями',
  tune_liftMs: 'Лифт: задержка, мс',
  tune_gentleSec: 'Без проигрыша, с',
  tune_rescueMs: 'Окно спасения, мс',
  tune_paceStartMs: 'Темп: интервал у цели на уровнях 1–3, мс',
  tune_paceRatio: 'Темп: множитель интервала за уровень',
  tune_paceMinMs: 'Темп: нижняя граница интервала, мс',
  tune_phaseLevels: 'Фаза: уровней в фазе',
  tune_breathLevels: 'Фаза: откат на первом уровне, уровней',
  tune_calmMs: 'Фаза: тишина в начале, мс',
  tune_refillEndMs: 'Интервал при недоборе к 15-му уровню, мс',
  tune_chainCalmMs: 'Цепочка: тишина за звено, мс',
  tune_chainCalmMaxMs: 'Цепочка: предел тишины, мс',
  tune_sinkStartMs: 'Окно цепочки в начале, мс',
  tune_sinkFloorMs: 'Окно цепочки к 20-му уровню, мс',
  tune_timedStartMs: '3 минуты: интервал у цели в начале, мс',
  tune_timedEndMs: '3 минуты: интервал у цели в конце, мс',
  tune_timedCalmMs: '3 минуты: отдых на границе минут, мс',
  cam_yaw: 'Поворот поля, °',
  cam_pitch: 'Высота камеры, °',
  cam_swipeTilt: 'Наклон свайпов к доске (0 — прямые)',
  puzzle: 'Пазл',
  undo: 'Отменить ход',
  cleared: 'Поле очищено',
  next: 'Дальше',
  puzzleStats: 'Статистика',
  share: 'Отправить',
  statsEmpty: 'Пока пусто: сыграй хотя бы один уровень',
  statsNote: 'Отправь этот текст автору игры: по нему настраивается сложность',
  play: 'Играть',
};

const EN: typeof RU = {
  score: 'SCORE',
  practice: 'PRACTICE',
  resume: 'Resume',
  restart: 'Restart',
  again: 'Again',
  playtest: 'Playtest',
  back: 'Back',
  result: 'Result',
  time: 'TIME',
  endless: 'Endless',
  timed: '3 minutes',
  tutorial: 'Tutorial',
  tune_timedSec: 'Time Limited length, s',
  experiments: 'Experiments',
  expNote: 'Rule changes apply from the next run',
  guidedStart: 'One-time hints during a run',
  gentleStart: 'No losing in the first 3 minutes',
  boardPreview: 'Face preview on the board',
  matchHint: 'Highlight the step that clears',
  floorClimb: 'Climb from the floor onto a cube that cannot be pushed',
  dockSteps: 'Docks are steps: down from a chain to the cell beside it at once, and up from it onto the cube next to it',
  floorLift: 'Lift: a player left on the floor gets the next cube under their feet',
  soloOne: 'A 1 at a chain sinks alone; the other 1s stay',
  chainCalm: 'A chain of two links or more holds regular cubes off while it runs and a little after',
  controls: 'Controls',
  gesture: 'Swipes',
  dpad: 'Buttons',
  replayTutorial: 'Replay tutorial',
  stats: 'Last run statistics',
  copy: 'Copy',
  copied: 'Copied',
  applyRestart: 'Apply and restart',
  noStats: 'No runs yet',
  records: 'Records',
  place: '#',
  sound: 'Sound',
  motion: 'Motion',
  shake: 'Shake',
  off: 'off',
  full: 'full',
  debugPanel: 'Debug panel for variables',
  debugTitle: 'Variables',
  debugRules: 'Gameplay · from the next run',
  debugCamera: 'Camera · live',
  reset: 'Reset',
  close: 'Close',
  tune_stepMs: 'Step, ms',
  tune_warnMs: 'Warning, ms',
  tune_riseMs: 'Cube rise, ms',
  tune_sinkMs: 'Sinking, ms',
  tune_spawnStartMs: 'Spawn interval at start, ms',
  tune_spawnStepMs: 'Speed-up per level, ms',
  tune_spawnMinMs: 'Minimum interval, ms',
  tune_cubesPerLevel: 'Cubes per level',
  tune_startCubes: 'Starting cubes',
  tune_lowHeight: 'Roll over a rising cube: below height',
  tune_sinkLowHeight: 'Roll over a sinking cube: below height',
  tune_mountHeight: 'Mount from the floor: below height',
  tune_stepDownHeight: 'Step off a sinking cube: below height',
  tune_chainLift: 'Chain: lift of the group on a join',
  tune_chainLiftMin: 'Chain: lift after five joins',
  tune_feedRate: 'Share of spawns that feed a chain',
  tune_helpRate: 'Share of helpful spawns',
  tune_targetCubes: 'Target number of cubes on the board',
  tune_refillMs: 'Interval below the target, ms',
  tune_sparseFactor: 'Interval at the target, x',
  tune_crowdedFactor: 'Interval on a crowded board, x',
  tune_easyLevels: 'Levels with easy faces',
  tune_liftMs: 'Lift delay, ms',
  tune_gentleSec: 'No-fail period, s',
  tune_rescueMs: 'Rescue window, ms',
  tune_paceStartMs: 'Pace: interval at the target on levels 1-3, ms',
  tune_paceRatio: 'Pace: interval multiplier per level',
  tune_paceMinMs: 'Pace: lowest interval, ms',
  tune_phaseLevels: 'Phase: levels in a phase',
  tune_breathLevels: 'Phase: levels back on its first level',
  tune_calmMs: 'Phase: silence at its start, ms',
  tune_refillEndMs: 'Interval below the target by level 15, ms',
  tune_chainCalmMs: 'Chain: silence per link, ms',
  tune_chainCalmMaxMs: 'Chain: longest silence, ms',
  tune_sinkStartMs: 'Chain window at the start, ms',
  tune_sinkFloorMs: 'Chain window by level 20, ms',
  tune_timedStartMs: 'Time Limited: interval at the target at the start, ms',
  tune_timedEndMs: 'Time Limited: interval at the target at the end, ms',
  tune_timedCalmMs: 'Time Limited: rest between minutes, ms',
  cam_yaw: 'Board turn, deg',
  cam_pitch: 'Camera height, deg',
  cam_swipeTilt: 'Swipes lean towards the board (0 is plain)',
  puzzle: 'Puzzle',
  undo: 'Undo move',
  cleared: 'Board cleared',
  next: 'Next',
  puzzleStats: 'Statistics',
  share: 'Send',
  statsEmpty: 'Nothing yet: play at least one level',
  statsNote: 'Send this text to the author of the game: the difficulty is tuned from it',
  play: 'Play',
};

export type DevKey = keyof typeof RU;

const lang = typeof navigator !== 'undefined' && navigator.language.toLowerCase().startsWith('ru') ? RU : EN;

/** A word of the tools. One that has not been written yet shows as its own key: these are tools. */
export function td(key: DevKey | (string & {})): string {
  return (lang as Record<string, string>)[key] ?? key;
}
