/**
 * The words of the development tools: the panel of the playtest, the report of the tasks, the
 * debug panel. Loaded with those tools, in development only.
 */
const RU = {
  score: 'SCORE',
  practice: 'PRACTICE',
  resume: 'Продолжить',
  restart: 'Заново',
  again: 'Ещё раз',
  playtest: 'Плейтест',
  back: 'Назад',
  result: 'Итог',
  time: 'TIME',
  endless: 'Бесконечный',
  timed: 'Сеанс дня',
  tutorial: 'Обучение',
  tune_timedSec: 'Длина сеанса дня, с',
  experiments: 'Эксперименты',
  expNote: 'Правила применяются со следующей партии',
  guidedStart: 'Разовые подсказки в партии',
  gentleStart: 'Первые минуты Endless без проигрыша',
  boardPreview: 'Превью грани на поле',
  matchHint: 'Подсветка шага, дающего очистку',
  floorClimb: 'С пола можно забраться на куб, который не толкается',
  dockSteps: 'Причалы — ступени: с цепочки на клетку рядом можно сойти сразу, с неё — подняться на соседний куб',
  floorLift: 'Лифт: если игрок остался на полу, следующий куб появляется под ним',
  soloOne: 'Единица у цепочки тонет одна, остальные единицы остаются',
  chainCalm: 'Цепочка от двух звеньев держит обычные кубы, пока идёт и ещё немного после, но не дольше предела подряд',
  timeFloor: 'Endless: уровень растёт и от времени, а не только от убранных кубов',
  waves: 'Кубы приходят волнами: нарастание, гребень, спад с полезными кубами; волны разной длины',
  surge: 'Гребень волны — залп: несколько кубов приходят разом',
  opening: 'Начало Endless: первый же перекат может собрать две двойки',
  lastSliver: 'Последняя полоска: за порогом опасности кубы приходят реже, очистка там один раз даёт тишину',
  gift: 'Подарок (Endless): после кубов без очистки приходит куб в одном повороте от группы, которой не хватает одного',
  controls: 'Управление',
  gesture: 'Жесты',
  dpad: 'Кнопки',
  replayTutorial: 'Повторить обучение',
  stats: 'Статистика последней партии',
  copy: 'Скопировать',
  copied: 'Скопировано',
  applyRestart: 'Применить и начать заново',
  noStats: 'Партий ещё не было',
  records: 'Рекорды',
  place: '№',
  sound: 'Звук',
  motion: 'Движение',
  shake: 'Тряска',
  off: 'выкл',
  full: 'полное',
  debugPanel: 'Дебаг-панель переменных',
  debugTitle: 'Переменные',
  debugRules: 'Геймплей · со следующей партии',
  debugCamera: 'Камера · сразу',
  reset: 'Сбросить',
  close: 'Закрыть',
  tune_stepMs: 'Шаг, мс',
  tune_warnMs: 'Предупреждение, мс',
  tune_riseMs: 'Подъём куба, мс',
  tune_sinkMs: 'Утопание, мс',
  tune_spawnStartMs: 'Интервал появления на старте, мс',
  tune_spawnStepMs: 'Ускорение за уровень, мс',
  tune_spawnMinMs: 'Минимальный интервал, мс',
  tune_cubesPerLevel: 'Кубов на уровень',
  tune_startCubes: 'Стартовых кубов',
  tune_lowHeight: 'Прокат по растущему кубу: ниже высоты',
  tune_sinkLowHeight: 'Прокат по тонущему кубу: ниже высоты',
  tune_mountHeight: 'Зайти на куб с пола: ниже высоты',
  tune_stepDownHeight: 'Сойти с тонущего куба: ниже высоты',
  tune_chainLift: 'Цепочка: подъём группы при добавлении',
  tune_chainLiftMin: 'Цепочка: подъём после пяти добавлений',
  tune_feedRate: 'Доля появлений под цепочку',
  tune_helpRate: 'Доля «полезных» появлений',
  tune_targetCubes: 'Целевое число кубов на поле',
  tune_refillMs: 'Интервал при недоборе, мс',
  tune_sparseFactor: 'Интервал при целевом числе, ×',
  tune_crowdedFactor: 'Интервал на тесном поле, ×',
  tune_easyLevels: 'Уровней с лёгкими гранями',
  tune_edgeFactor: 'Край: интервал на полном поле, ×',
  tune_edgeCalmMs: 'Край: тишина за очистку у порога опасности, мс',
  tune_giftRate: 'Подарок: прибавка шанса за каждый куб без очистки',
  tune_giftMax: 'Подарок: потолок шанса',
  tune_liftMs: 'Лифт: задержка, мс',
  tune_gentleSec: 'Endless без проигрыша, с',
  tune_rescueMs: 'Окно спасения, мс',
  tune_paceStartMs: 'Темп: интервал у цели на первых уровнях, мс',
  tune_paceFlatLevels: 'Темп: уровней без разгона в начале',
  tune_levelSec: 'Уровень от времени: секунд на уровень',
  tune_paceGrowth: 'Темп: прибавка потока за уровень, доля стартового',
  tune_paceMinMs: 'Темп: нижняя граница интервала, мс',
  tune_waveSec: 'Волна: нарастание в среднем, с',
  tune_waveSpread: 'Волна: разброс длин волн и тишины, доля',
  tune_waveEase: 'Волна: интервал в начале волны, ×',
  tune_wavePeak: 'Волна: интервал на гребне, ×',
  tune_restMs: 'Волна: спад после гребня в среднем, мс',
  tune_restFlow: 'Волна: доля потока во время спада (0 — тишина)',
  tune_surgeCubes: 'Гребень: кубов в залпе на первых волнах',
  tune_surgeMax: 'Гребень: кубов в залпе самое большее',
  tune_breatherEvery: 'Большая передышка: раз в сколько волн (0 — нет)',
  tune_breatherFactor: 'Большая передышка: во сколько раз длиннее спад',
  tune_wipeBonus: 'Чистое поле: очков за уровень (0 — нет)',
  tune_refillEndMs: 'Интервал при недоборе к 15-му уровню, мс',
  tune_chainCalmMs: 'Цепочка: тишина за звено, мс',
  tune_chainCalmMaxMs: 'Цепочка: предел тишины подряд, мс',
  tune_sinkStartMs: 'Окно цепочки в начале, мс',
  tune_sinkFloorMs: 'Окно цепочки к 20-му уровню, мс',
  tune_timedStartMs: 'Сеанс дня: интервал у цели в начале, мс',
  tune_timedEndMs: 'Сеанс дня: интервал у цели в конце, мс',
  cam_yaw: 'Поворот поля, °',
  cam_pitch: 'Высота камеры, °',
  cam_swipeTilt: 'Наклон свайпов к доске (0 — прямые)',
  puzzle: 'Пазл',
  undo: 'Отменить ход',
  cleared: 'Поле очищено',
  next: 'Дальше',
  puzzleStats: 'Статистика',
  share: 'Отправить',
  statsEmpty: 'Пока пусто: сыграй хотя бы один уровень',
  statsNote: 'Отправь этот текст автору игры: по нему настраивается сложность',
  play: 'Играть',
};

const EN: typeof RU = {
  score: 'SCORE',
  practice: 'PRACTICE',
  resume: 'Resume',
  restart: 'Restart',
  again: 'Again',
  playtest: 'Playtest',
  back: 'Back',
  result: 'Result',
  time: 'TIME',
  endless: 'Endless',
  timed: 'Session of the day',
  tutorial: 'Tutorial',
  tune_timedSec: 'Session of the day: length, s',
  experiments: 'Experiments',
  expNote: 'Rule changes apply from the next run',
  guidedStart: 'One-time hints during a run',
  gentleStart: 'No losing in the first minutes of Endless',
  boardPreview: 'Face preview on the board',
  matchHint: 'Highlight the step that clears',
  floorClimb: 'Climb from the floor onto a cube that cannot be pushed',
  dockSteps: 'Docks are steps: down from a chain to the cell beside it at once, and up from it onto the cube next to it',
  floorLift: 'Lift: a player left on the floor gets the next cube under their feet',
  soloOne: 'A 1 at a chain sinks alone; the other 1s stay',
  chainCalm: 'A chain of two links or more holds regular cubes off while it runs and a little after, up to a limit in one stretch',
  timeFloor: 'Endless: the level rises with the time too, not only with the cubes removed',
  waves: 'Cubes come in waves: a build, a crest, a trough of helpful cubes; no two waves of one length',
  surge: 'The crest of a wave is a salvo: several cubes come at once',
  opening: 'The opening of Endless: the very first roll can clear two 2s',
  lastSliver: 'The last sliver: past the danger mark cubes come slower, and a clear there holds them off once',
  gift: 'A gift (Endless): after cubes with no clear, a cube comes one roll away from a group that lacks one die',
  controls: 'Controls',
  gesture: 'Swipes',
  dpad: 'Buttons',
  replayTutorial: 'Replay tutorial',
  stats: 'Last run statistics',
  copy: 'Copy',
  copied: 'Copied',
  applyRestart: 'Apply and restart',
  noStats: 'No runs yet',
  records: 'Records',
  place: '#',
  sound: 'Sound',
  motion: 'Motion',
  shake: 'Shake',
  off: 'off',
  full: 'full',
  debugPanel: 'Debug panel for variables',
  debugTitle: 'Variables',
  debugRules: 'Gameplay · from the next run',
  debugCamera: 'Camera · live',
  reset: 'Reset',
  close: 'Close',
  tune_stepMs: 'Step, ms',
  tune_warnMs: 'Warning, ms',
  tune_riseMs: 'Cube rise, ms',
  tune_sinkMs: 'Sinking, ms',
  tune_spawnStartMs: 'Spawn interval at start, ms',
  tune_spawnStepMs: 'Speed-up per level, ms',
  tune_spawnMinMs: 'Minimum interval, ms',
  tune_cubesPerLevel: 'Cubes per level',
  tune_startCubes: 'Starting cubes',
  tune_lowHeight: 'Roll over a rising cube: below height',
  tune_sinkLowHeight: 'Roll over a sinking cube: below height',
  tune_mountHeight: 'Mount from the floor: below height',
  tune_stepDownHeight: 'Step off a sinking cube: below height',
  tune_chainLift: 'Chain: lift of the group on a join',
  tune_chainLiftMin: 'Chain: lift after five joins',
  tune_feedRate: 'Share of spawns that feed a chain',
  tune_helpRate: 'Share of helpful spawns',
  tune_targetCubes: 'Target number of cubes on the board',
  tune_refillMs: 'Interval below the target, ms',
  tune_sparseFactor: 'Interval at the target, x',
  tune_crowdedFactor: 'Interval on a crowded board, x',
  tune_easyLevels: 'Levels with easy faces',
  tune_edgeFactor: 'Edge: interval on a full board, x',
  tune_edgeCalmMs: 'Edge: silence for a clear at the danger mark, ms',
  tune_giftRate: 'Gift: chance added by every cube with no clear',
  tune_giftMax: 'Gift: highest chance',
  tune_liftMs: 'Lift delay, ms',
  tune_gentleSec: 'Endless: no-fail period, s',
  tune_rescueMs: 'Rescue window, ms',
  tune_paceStartMs: 'Pace: interval at the target on the first levels, ms',
  tune_paceFlatLevels: 'Pace: levels at the start with no speed-up',
  tune_levelSec: 'Level by the clock: seconds per level',
  tune_paceGrowth: 'Pace: flow added per level, share of the starting flow',
  tune_paceMinMs: 'Pace: lowest interval, ms',
  tune_waveSec: 'Wave: build on average, s',
  tune_waveSpread: 'Wave: spread of the lengths of waves and silences, share',
  tune_waveEase: 'Wave: interval where a wave opens, x',
  tune_wavePeak: 'Wave: interval at the crest, x',
  tune_restMs: 'Wave: trough after the crest on average, ms',
  tune_restFlow: 'Wave: share of the flow in the trough (0 is a silence)',
  tune_surgeCubes: 'Crest: cubes in the salvo on the first waves',
  tune_surgeMax: 'Crest: most cubes in the salvo',
  tune_breatherEvery: 'Big breather: once in how many waves (0 is never)',
  tune_breatherFactor: 'Big breather: how many times longer the trough',
  tune_wipeBonus: 'Clean board: points per level (0 is none)',
  tune_refillEndMs: 'Interval below the target by level 15, ms',
  tune_chainCalmMs: 'Chain: silence per link, ms',
  tune_chainCalmMaxMs: 'Chain: longest silence in one stretch, ms',
  tune_sinkStartMs: 'Chain window at the start, ms',
  tune_sinkFloorMs: 'Chain window by level 20, ms',
  tune_timedStartMs: 'Session of the day: interval at the target at the start, ms',
  tune_timedEndMs: 'Session of the day: interval at the target at the end, ms',
  cam_yaw: 'Board turn, deg',
  cam_pitch: 'Camera height, deg',
  cam_swipeTilt: 'Swipes lean towards the board (0 is plain)',
  puzzle: 'Puzzle',
  undo: 'Undo move',
  cleared: 'Board cleared',
  next: 'Next',
  puzzleStats: 'Statistics',
  share: 'Send',
  statsEmpty: 'Nothing yet: play at least one level',
  statsNote: 'Send this text to the author of the game: the difficulty is tuned from it',
  play: 'Play',
};

export type DevKey = keyof typeof RU;

const lang = typeof navigator !== 'undefined' && navigator.language.toLowerCase().startsWith('ru') ? RU : EN;

/** A word of the tools. One that has not been written yet shows as its own key: these are tools. */
export function td(key: DevKey | (string & {})): string {
  return (lang as Record<string, string>)[key] ?? key;
}
