import type { LevelSpec } from '../rules/types';

/**
 * The levels of the game: the probe, a first batch made to find what a level of this game is.
 * Every level is a board to clear, given die by die: nothing comes to it. Only the faces a level
 * names work on it, and a die that has joined a combo goes in two moves. The floor is open and
 * strict: a die is rolled from on top and pushed from the floor, and the one way up is a die
 * that is leaving. A level is lost at a dead end: too few dice standing for a combo with nothing
 * going, or the player down on the floor with nothing to push and nothing to go up by, or with
 * too few faces that work. As it is kept here a level has no limit of moves; played, it has the
 * generous one of its chapter, laid on it by `progress.ts`, which also rates a pass with stars.
 *
 * The batch teaches nothing: no level says a rule or shows a move. It is played by one who knows
 * the rules, by number and blind, and every level is open. What a level is there for is not said
 * here: a level is a place of `recipes.ts`, the place is a form, and which is which is in the
 * key, docs/VI_Levels_Probe_Key.md. The order was shuffled once and is kept.
 *
 * The boards are not drawn by hand. They are picked by `node scripts/ladder.mjs place=P06` among
 * the boards laid by the recipe of each place: built from its route backwards (`route.ts`),
 * solved to the fewest moves, the route and the score of the way held against what the form
 * asks for, the parts of the route it leans on proved to have no way round. `seed` is the seed
 * the board was laid from, kept for the record: a level is its dice. `solution` is a way of
 * `par` moves, and the test of this list plays it.
 *
 * The levels that were here before, the course and the chapters, are in the history: commit
 * 534b3ea.
 */
export const LEVELS: readonly LevelSpec[] = [
  { id: 'P01', chapter: 0, seed: 30762, size: 3, values: [3], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['0,1,N', '0,0,E', '1,1,W', '0,2,E', '1,2,N', '0,1,N'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 1, top: 5, north: 6 }, { x: 1, z: 1, top: 5, north: 4 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 0, z: 2, top: 6, north: 4 }] } },
  { id: 'P02', chapter: 0, seed: 30842, size: 4, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,2,E', '2,2,S', '3,2,W', '2,2,W'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 2, top: 6, north: 2 }, { x: 3, z: 2, top: 5, north: 6 }, { x: 1, z: 3, top: 2, north: 3 }, { x: 3, z: 3, top: 2, north: 3 }] } },
  { id: 'P03', chapter: 0, seed: 30042, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 7, exact: true, solution: ['2,2,N', '2,1,N', '2,0,W', '1,2,E', '2,2,N', '1,0,E', '1,1,N'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 1, z: 1, top: 6, north: 4 }, { x: 1, z: 2, top: 6, north: 4 }, { x: 2, z: 2, top: 4, north: 1 }] } },
  { id: 'P04', chapter: 0, seed: 30787, size: 4, values: [5], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['0,0,E', '1,0,E', '2,1,S', '2,2,S'], layout: { start: { x: 0, z: 0 }, dice: [{ x: 0, z: 0, top: 2, north: 1 }, { x: 3, z: 0, top: 5, north: 6 }, { x: 2, z: 1, top: 2, north: 6 }, { x: 3, z: 1, top: 5, north: 6 }, { x: 3, z: 2, top: 5, north: 1 }, { x: 3, z: 3, top: 5, north: 6 }] } },
  { id: 'P05', chapter: 0, seed: 30471, size: 3, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['0,0,S', '1,2,W', '0,1,N', '1,1,S', '2,1,W', '2,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 0, top: 3, north: 5 }, { x: 1, z: 0, top: 3, north: 2 }, { x: 1, z: 1, top: 5, north: 3 }, { x: 2, z: 1, top: 5, north: 1 }, { x: 1, z: 2, top: 5, north: 1 }, { x: 2, z: 2, top: 5, north: 4 }] } },
  { id: 'P06', chapter: 0, seed: 30282, size: 4, values: [2], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['3,0,W', '2,0,W', '3,2,S,p', '2,2,E'], layout: { start: { x: 3, z: 0 }, dice: [{ x: 3, z: 0, top: 5, north: 4 }, { x: 1, z: 1, top: 2, north: 1 }, { x: 2, z: 2, top: 6, north: 4 }, { x: 3, z: 2, top: 2, north: 1 }, { x: 2, z: 3, top: 2, north: 4 }] } },
  { id: 'P07', chapter: 0, seed: 33100, size: 3, values: [2, 3], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['2,1,N', '2,0,W', '0,2,E', '0,1,N'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 0, z: 1, top: 2, north: 4 }, { x: 1, z: 1, top: 3, north: 5 }, { x: 2, z: 1, top: 5, north: 1 }, { x: 0, z: 2, top: 3, north: 6 }, { x: 2, z: 2, top: 2, north: 3 }] } },
  { id: 'P08', chapter: 0, seed: 30967, size: 4, values: [2], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['3,0,W', '2,0,W', '0,0,S', '0,2,E', '2,2,N'], layout: { start: { x: 3, z: 0 }, dice: [{ x: 0, z: 0, top: 3, north: 2 }, { x: 3, z: 0, top: 5, north: 6 }, { x: 1, z: 1, top: 2, north: 1 }, { x: 0, z: 2, top: 3, north: 6 }, { x: 2, z: 2, top: 6, north: 5 }] } },
  { id: 'P09', chapter: 0, seed: 30551, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['3,3,W', '1,2,N', '1,0,E', '1,1,S', '1,2,E'], layout: { start: { x: 3, z: 3 }, dice: [{ x: 1, z: 0, top: 2, north: 1 }, { x: 3, z: 0, top: 3, north: 6 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 1, z: 2, top: 6, north: 2 }, { x: 1, z: 3, top: 3, north: 2 }, { x: 3, z: 3, top: 6, north: 5 }] } },
  { id: 'P10', chapter: 0, seed: 30974, size: 4, values: [1, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [1, 3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,3,N', '2,3,E', '3,3,N', '1,1,E,p'], layout: { start: { x: 2, z: 3 }, dice: [{ x: 1, z: 1, top: 1, north: 4 }, { x: 3, z: 1, top: 3, north: 6 }, { x: 0, z: 2, top: 1, north: 5 }, { x: 2, z: 2, top: 3, north: 5 }, { x: 1, z: 3, top: 3, north: 6 }, { x: 2, z: 3, top: 2, north: 4 }] } },
  { id: 'P11', chapter: 0, seed: 30034, size: 4, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['0,0,S', '0,1,S', '1,2,E', '2,2,N', '2,1,W', '1,1,W'], layout: { start: { x: 0, z: 0 }, dice: [{ x: 0, z: 0, top: 5, north: 3 }, { x: 1, z: 2, top: 6, north: 2 }] } },
  { id: 'P12', chapter: 0, seed: 30544, size: 4, values: [2, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['2,3,W', '1,3,W', '1,2,N,p', '3,0,W'], layout: { start: { x: 2, z: 3 }, dice: [{ x: 3, z: 0, top: 5, north: 1 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 3, z: 1, top: 3, north: 5 }, { x: 0, z: 2, top: 2, north: 6 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 2, z: 3, top: 5, north: 1 }] } },
  { id: 'P13', chapter: 0, seed: 30120, size: 4, values: [6], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [6], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['1,0,S', '2,2,E', '3,2,N', '1,2,E', '1,1,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 0, top: 6, north: 5 }, { x: 2, z: 0, top: 6, north: 3 }, { x: 3, z: 0, top: 6, north: 2 }, { x: 2, z: 1, top: 6, north: 3 }, { x: 1, z: 2, top: 3, north: 5 }, { x: 2, z: 2, top: 3, north: 1 }] } },
  { id: 'P14', chapter: 0, seed: 30627, size: 4, values: [4], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,1,E', '2,1,E', '1,0,E,p', '2,0,E,p'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 1, z: 0, top: 4, north: 5 }, { x: 1, z: 1, top: 3, north: 6 }, { x: 2, z: 2, top: 4, north: 1 }, { x: 3, z: 2, top: 4, north: 2 }, { x: 2, z: 3, top: 4, north: 5 }] } },
  { id: 'P15', chapter: 0, seed: 31888, size: 3, values: [2, 3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['2,1,N', '1,2,N', '1,1,E', '0,1,E', '1,0,S', '1,1,W'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 0, z: 0, top: 2, north: 4 }, { x: 1, z: 0, top: 4, north: 6 }, { x: 0, z: 1, top: 6, north: 2 }, { x: 2, z: 1, top: 2, north: 4 }, { x: 0, z: 2, top: 2, north: 6 }, { x: 1, z: 2, top: 5, north: 6 }, { x: 2, z: 2, top: 3, north: 2 }] } },
  { id: 'P16', chapter: 0, seed: 31570, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,1,S', '2,3,W', '1,2,W', '1,3,N'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 1, top: 3, north: 2 }, { x: 1, z: 1, top: 6, north: 5 }, { x: 2, z: 2, top: 3, north: 6 }, { x: 3, z: 2, top: 3, north: 5 }, { x: 0, z: 3, top: 3, north: 2 }, { x: 2, z: 3, top: 6, north: 4 }] } },
  { id: 'P17', chapter: 0, seed: 30072, size: 4, values: [3, 4], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3, 4], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,2,E', '0,0,S', '0,2,E', '2,2,E'], layout: { start: { x: 0, z: 0 }, dice: [{ x: 0, z: 0, top: 5, north: 4 }, { x: 1, z: 0, top: 4, north: 6 }, { x: 1, z: 1, top: 4, north: 1 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 3, z: 1, top: 3, north: 2 }, { x: 0, z: 2, top: 2, north: 6 }, { x: 1, z: 2, top: 4, north: 6 }] } },
  { id: 'P18', chapter: 0, seed: 30665, size: 4, values: [1, 4], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [1, 4], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['0,3,N', '1,0,E', '2,1,W', '1,1,S', '2,0,W,p'], layout: { start: { x: 0, z: 3 }, dice: [{ x: 0, z: 0, top: 4, north: 1 }, { x: 1, z: 0, top: 3, north: 2 }, { x: 0, z: 1, top: 4, north: 6 }, { x: 2, z: 1, top: 5, north: 4 }, { x: 0, z: 3, top: 6, north: 3 }, { x: 2, z: 3, top: 1, north: 2 }] } },
  { id: 'P19', chapter: 0, seed: 30263, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['2,3,E', '3,3,N', '3,2,N', '1,1,W,p', '0,1,S,p'], layout: { start: { x: 2, z: 3 }, dice: [{ x: 2, z: 0, top: 3, north: 6 }, { x: 3, z: 0, top: 3, north: 6 }, { x: 1, z: 1, top: 3, north: 2 }, { x: 1, z: 2, top: 3, north: 2 }, { x: 0, z: 3, top: 3, north: 1 }, { x: 2, z: 3, top: 6, north: 5 }] } },
  { id: 'P20', chapter: 0, seed: 30084, size: 4, values: [3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['2,3,N', '2,2,W', '2,1,S', '0,2,S', '0,1,S', '3,2,W'], layout: { start: { x: 1, z: 3 }, dice: [{ x: 0, z: 1, top: 2, north: 3 }, { x: 1, z: 1, top: 3, north: 2 }, { x: 2, z: 1, top: 6, north: 3 }, { x: 0, z: 2, top: 5, north: 3 }, { x: 3, z: 2, top: 5, north: 1 }, { x: 1, z: 3, top: 3, north: 5 }, { x: 2, z: 3, top: 5, north: 1 }] } },
];

/**
 * Boards in reserve: for a place of the probe, the boards that fit it next best. They take a
 * level's place when a playtest asks for another board of the same form.
 */
export const SPARES: readonly LevelSpec[] = [
  { id: 'P01', chapter: 0, seed: 30512, size: 3, values: [3], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['1,1,S', '0,0,E', '1,0,E', '2,0,S', '2,1,W', '0,1,S'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 0, z: 0, top: 5, north: 6 }, { x: 0, z: 1, top: 6, north: 3 }, { x: 1, z: 1, top: 5, north: 3 }, { x: 0, z: 2, top: 3, north: 2 }] } },
  { id: 'P01', chapter: 0, seed: 30192, size: 3, values: [3], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['1,1,W', '1,0,S', '2,1,S', '2,2,W', '0,1,S', '1,1,W'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 0, z: 0, top: 3, north: 2 }, { x: 1, z: 0, top: 5, north: 1 }, { x: 1, z: 1, top: 2, north: 3 }, { x: 2, z: 1, top: 5, north: 1 }] } },
  { id: 'P02', chapter: 0, seed: 31295, size: 4, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 3, exact: true, solution: ['1,1,E', '2,1,N', '3,1,N'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 1, z: 0, top: 2, north: 6 }, { x: 3, z: 0, top: 2, north: 3 }, { x: 1, z: 1, top: 3, north: 5 }, { x: 3, z: 1, top: 3, north: 5 }] } },
  { id: 'P02', chapter: 0, seed: 30214, size: 4, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 3, exact: true, solution: ['1,1,N', '0,1,E', '1,1,E'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 0, top: 2, north: 6 }, { x: 2, z: 0, top: 2, north: 1 }, { x: 0, z: 1, top: 5, north: 6 }, { x: 1, z: 1, top: 4, north: 5 }] } },
  { id: 'P03', chapter: 0, seed: 30146, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 7, exact: true, solution: ['0,0,E', '1,0,E', '2,0,S', '0,1,N', '0,0,E', '2,1,N', '1,1,E'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 0, z: 0, top: 4, north: 2 }, { x: 0, z: 1, top: 2, north: 1 }, { x: 1, z: 1, top: 6, north: 2 }] } },
  { id: 'P04', chapter: 0, seed: 31783, size: 4, values: [5], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['3,3,N', '3,2,W', '2,3,W', '1,3,W'], layout: { start: { x: 2, z: 3 }, dice: [{ x: 0, z: 0, top: 5, north: 4 }, { x: 0, z: 1, top: 5, north: 4 }, { x: 0, z: 2, top: 5, north: 1 }, { x: 1, z: 2, top: 5, north: 4 }, { x: 2, z: 3, top: 2, north: 3 }, { x: 3, z: 3, top: 4, north: 1 }] } },
  { id: 'P04', chapter: 0, seed: 30207, size: 4, values: [5], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['3,1,W', '2,1,W', '0,1,S', '0,2,S'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 0, z: 1, top: 2, north: 6 }, { x: 3, z: 1, top: 2, north: 1 }, { x: 1, z: 2, top: 5, north: 6 }, { x: 1, z: 3, top: 5, north: 6 }, { x: 2, z: 3, top: 5, north: 6 }, { x: 3, z: 3, top: 5, north: 1 }] } },
  { id: 'P05', chapter: 0, seed: 30158, size: 3, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['1,1,S', '1,0,S', '0,0,E', '1,2,E', '0,1,E', '1,1,S'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 0, z: 0, top: 5, north: 6 }, { x: 1, z: 0, top: 6, north: 3 }, { x: 0, z: 1, top: 6, north: 3 }, { x: 1, z: 1, top: 6, north: 2 }, { x: 2, z: 1, top: 3, north: 5 }, { x: 0, z: 2, top: 3, north: 5 }] } },
  { id: 'P05', chapter: 0, seed: 30236, size: 3, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['1,1,E', '2,1,N', '0,1,E', '0,0,S', '1,2,N', '1,1,E'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 0, z: 0, top: 6, north: 3 }, { x: 1, z: 0, top: 3, north: 6 }, { x: 0, z: 1, top: 5, north: 6 }, { x: 1, z: 1, top: 5, north: 4 }, { x: 1, z: 2, top: 2, north: 1 }, { x: 2, z: 2, top: 3, north: 5 }] } },
  { id: 'P06', chapter: 0, seed: 30377, size: 4, values: [2], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['2,1,W', '1,1,N', '0,2,S,p', '1,2,W'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 0, z: 0, top: 2, north: 3 }, { x: 2, z: 1, top: 4, north: 5 }, { x: 0, z: 2, top: 2, north: 4 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 1, z: 3, top: 2, north: 3 }] } },
  { id: 'P06', chapter: 0, seed: 30399, size: 4, values: [2], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['3,3,N', '1,1,S,p', '2,3,W,p', '1,3,W'], layout: { start: { x: 3, z: 3 }, dice: [{ x: 1, z: 1, top: 2, north: 6 }, { x: 3, z: 1, top: 2, north: 4 }, { x: 0, z: 2, top: 2, north: 1 }, { x: 2, z: 3, top: 6, north: 3 }, { x: 3, z: 3, top: 3, north: 5 }] } },
  { id: 'P07', chapter: 0, seed: 31151, size: 3, values: [2, 3], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,1,S', '2,1,N', '2,0,W', '0,1,E'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 0, z: 0, top: 2, north: 4 }, { x: 0, z: 1, top: 5, north: 6 }, { x: 1, z: 1, top: 2, north: 3 }, { x: 2, z: 1, top: 6, north: 3 }, { x: 2, z: 2, top: 3, north: 2 }] } },
  { id: 'P07', chapter: 0, seed: 32873, size: 3, values: [2, 3], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,2,W', '1,0,W', '2,1,S', '2,2,W'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 1, z: 0, top: 4, north: 6 }, { x: 0, z: 1, top: 2, north: 6 }, { x: 1, z: 1, top: 3, north: 2 }, { x: 2, z: 1, top: 2, north: 6 }, { x: 1, z: 2, top: 5, north: 1 }] } },
  { id: 'P08', chapter: 0, seed: 30006, size: 4, values: [2], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['1,2,E', '2,2,N', '3,0,S', '3,2,W', '2,3,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 2, z: 0, top: 2, north: 3 }, { x: 3, z: 0, top: 3, north: 2 }, { x: 1, z: 2, top: 6, north: 5 }, { x: 3, z: 2, top: 4, north: 6 }, { x: 2, z: 3, top: 6, north: 5 }] } },
  { id: 'P08', chapter: 0, seed: 30370, size: 4, values: [2], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['1,2,E', '2,2,N', '3,0,W', '1,1,N', '0,0,E'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 0, top: 4, north: 1 }, { x: 3, z: 0, top: 6, north: 3 }, { x: 1, z: 1, top: 4, north: 5 }, { x: 3, z: 1, top: 2, north: 3 }, { x: 1, z: 2, top: 3, north: 5 }] } },
  { id: 'P09', chapter: 0, seed: 30009, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['2,1,E', '3,1,S', '3,3,W', '1,3,N', '2,3,W'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 1, top: 6, north: 3 }, { x: 0, z: 2, top: 3, north: 2 }, { x: 2, z: 2, top: 3, north: 1 }, { x: 0, z: 3, top: 3, north: 1 }, { x: 1, z: 3, top: 2, north: 4 }, { x: 3, z: 3, top: 4, north: 6 }] } },
  { id: 'P09', chapter: 0, seed: 30848, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['0,1,E', '0,2,E', '1,2,E', '2,3,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 2, z: 0, top: 3, north: 6 }, { x: 0, z: 1, top: 5, north: 6 }, { x: 2, z: 1, top: 3, north: 5 }, { x: 0, z: 2, top: 4, north: 6 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 2, z: 3, top: 6, north: 4 }] } },
  { id: 'P10', chapter: 0, seed: 30582, size: 4, values: [1, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [1, 3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['2,1,W', '1,1,N', '1,2,N,p', '3,2,N,p'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 0, top: 3, north: 5 }, { x: 3, z: 0, top: 3, north: 6 }, { x: 2, z: 1, top: 2, north: 4 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 3, z: 2, top: 1, north: 2 }, { x: 0, z: 3, top: 1, north: 2 }] } },
  { id: 'P10', chapter: 0, seed: 30882, size: 4, values: [1, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [1, 3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['2,2,S', '2,3,E', '2,1,E', '1,3,E,p'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 0, z: 1, top: 1, north: 5 }, { x: 2, z: 1, top: 5, north: 6 }, { x: 3, z: 1, top: 3, north: 2 }, { x: 2, z: 2, top: 6, north: 2 }, { x: 3, z: 2, top: 3, north: 5 }, { x: 1, z: 3, top: 1, north: 4 }] } },
  { id: 'P11', chapter: 0, seed: 30154, size: 4, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,3,N', '1,2,N', '1,0,E', '2,0,S'], layout: { start: { x: 1, z: 3 }, dice: [{ x: 1, z: 0, top: 6, north: 2 }, { x: 1, z: 3, top: 5, north: 1 }] } },
  { id: 'P12', chapter: 0, seed: 30002, size: 4, values: [2, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['3,1,W', '3,2,S,p', '0,2,S,p', '3,3,W', '2,3,W'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 1, z: 1, top: 2, north: 4 }, { x: 3, z: 1, top: 3, north: 1 }, { x: 0, z: 2, top: 3, north: 6 }, { x: 3, z: 2, top: 4, north: 2 }, { x: 1, z: 3, top: 3, north: 1 }, { x: 2, z: 3, top: 3, north: 6 }] } },
  { id: 'P12', chapter: 0, seed: 30376, size: 4, values: [2, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['2,0,E', '1,1,W,p', '1,3,W,p', '0,3,N'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 0, z: 0, top: 3, north: 2 }, { x: 2, z: 0, top: 4, north: 1 }, { x: 1, z: 1, top: 3, north: 6 }, { x: 3, z: 1, top: 2, north: 6 }, { x: 0, z: 2, top: 3, north: 6 }, { x: 1, z: 3, top: 2, north: 4 }] } },
  { id: 'P13', chapter: 0, seed: 30460, size: 4, values: [6], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [6], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['0,1,N', '0,0,E', '1,0,S', '2,2,S', '2,3,W'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 1, top: 6, north: 5 }, { x: 2, z: 1, top: 6, north: 5 }, { x: 0, z: 2, top: 6, north: 2 }, { x: 1, z: 2, top: 6, north: 3 }, { x: 2, z: 2, top: 3, north: 2 }, { x: 0, z: 3, top: 6, north: 5 }] } },
  { id: 'P13', chapter: 0, seed: 30065, size: 4, values: [6], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [6], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['1,1,W', '0,1,S', '0,2,E', '2,1,E', '3,1,S'], layout: { start: { x: 2, z: 3 }, dice: [{ x: 1, z: 1, top: 6, north: 4 }, { x: 2, z: 1, top: 4, north: 6 }, { x: 2, z: 2, top: 6, north: 5 }, { x: 1, z: 3, top: 6, north: 2 }, { x: 2, z: 3, top: 6, north: 2 }, { x: 3, z: 3, top: 6, north: 5 }] } },
  { id: 'P14', chapter: 0, seed: 30615, size: 4, values: [4], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['2,2,W', '1,2,W', '2,0,W,p', '1,0,W,p'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 2, z: 0, top: 4, north: 2 }, { x: 0, z: 1, top: 4, north: 2 }, { x: 2, z: 2, top: 3, north: 5 }, { x: 0, z: 3, top: 4, north: 1 }, { x: 1, z: 3, top: 4, north: 2 }] } },
  { id: 'P14', chapter: 0, seed: 30797, size: 4, values: [4], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,0,W', '0,0,S', '2,0,W,p', '1,0,W,p'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 1, z: 0, top: 6, north: 4 }, { x: 2, z: 0, top: 4, north: 1 }, { x: 0, z: 2, top: 4, north: 6 }, { x: 0, z: 3, top: 4, north: 5 }, { x: 1, z: 3, top: 4, north: 6 }] } },
  { id: 'P15', chapter: 0, seed: 31571, size: 3, values: [2, 3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['0,1,E', '0,0,S', '2,2,N', '1,2,E', '1,1,S', '0,1,E'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 0, z: 0, top: 4, north: 1 }, { x: 1, z: 0, top: 2, north: 4 }, { x: 2, z: 0, top: 3, north: 1 }, { x: 0, z: 1, top: 3, north: 2 }, { x: 0, z: 2, top: 2, north: 1 }, { x: 1, z: 2, top: 6, north: 2 }, { x: 2, z: 2, top: 6, north: 4 }] } },
  { id: 'P15', chapter: 0, seed: 30402, size: 3, values: [2, 3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['0,1,N', '1,2,N', '1,1,W', '2,1,W', '1,1,S', '2,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 0, top: 3, north: 5 }, { x: 2, z: 0, top: 2, north: 3 }, { x: 0, z: 1, top: 5, north: 4 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 0, z: 2, top: 2, north: 6 }, { x: 1, z: 2, top: 6, north: 5 }, { x: 2, z: 2, top: 6, north: 5 }] } },
  { id: 'P16', chapter: 0, seed: 31722, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['3,1,S', '3,2,W', '3,3,N', '3,2,N'], layout: { start: { x: 3, z: 0 }, dice: [{ x: 3, z: 0, top: 3, north: 5 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 3, z: 1, top: 5, north: 1 }, { x: 1, z: 3, top: 3, north: 5 }, { x: 2, z: 3, top: 3, north: 5 }, { x: 3, z: 3, top: 4, north: 5 }] } },
  { id: 'P16', chapter: 0, seed: 31055, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,0,E', '2,0,S', '3,0,W', '2,0,W'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 1, z: 0, top: 6, north: 3 }, { x: 3, z: 0, top: 4, north: 2 }, { x: 0, z: 1, top: 3, north: 6 }, { x: 1, z: 1, top: 3, north: 1 }, { x: 3, z: 1, top: 3, north: 1 }, { x: 3, z: 2, top: 3, north: 5 }] } },
  { id: 'P17', chapter: 0, seed: 30075, size: 4, values: [3, 4], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3, 4], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['2,1,S', '1,1,E', '1,0,S', '2,2,S', '1,2,W'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 0, top: 6, north: 3 }, { x: 2, z: 0, top: 3, north: 1 }, { x: 1, z: 1, top: 5, north: 6 }, { x: 2, z: 1, top: 3, north: 1 }, { x: 1, z: 2, top: 2, north: 1 }, { x: 0, z: 3, top: 4, north: 1 }, { x: 1, z: 3, top: 4, north: 6 }] } },
  { id: 'P17', chapter: 0, seed: 31123, size: 4, values: [3, 4], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3, 4], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['0,1,E', '0,2,N', '1,2,W', '1,1,E', '3,0,S'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 0, z: 0, top: 3, north: 6 }, { x: 1, z: 0, top: 4, north: 2 }, { x: 2, z: 0, top: 4, north: 5 }, { x: 3, z: 0, top: 5, north: 4 }, { x: 0, z: 1, top: 3, north: 5 }, { x: 0, z: 2, top: 6, north: 4 }, { x: 1, z: 2, top: 6, north: 5 }] } },
  { id: 'P18', chapter: 0, seed: 30105, size: 4, values: [1, 4], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [1, 4], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['0,0,E', '1,0,S', '2,0,W', '0,3,E', '2,1,S,p'], layout: { start: { x: 0, z: 0 }, dice: [{ x: 0, z: 0, top: 2, north: 4 }, { x: 2, z: 0, top: 4, north: 2 }, { x: 2, z: 1, top: 1, north: 2 }, { x: 0, z: 2, top: 4, north: 5 }, { x: 1, z: 2, top: 4, north: 2 }, { x: 0, z: 3, top: 2, north: 6 }] } },
  { id: 'P18', chapter: 0, seed: 30824, size: 4, values: [1, 4], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [1, 4], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['1,0,E', '2,0,S', '1,1,S', '0,2,S', '2,1,S,p'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 1, z: 0, top: 5, north: 1 }, { x: 1, z: 1, top: 2, north: 4 }, { x: 0, z: 2, top: 6, north: 4 }, { x: 3, z: 2, top: 1, north: 5 }, { x: 1, z: 3, top: 4, north: 5 }, { x: 2, z: 3, top: 4, north: 5 }] } },
  { id: 'P19', chapter: 0, seed: 30721, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['3,2,W', '2,2,S', '2,3,W', '1,1,N,p'], layout: { start: { x: 3, z: 2 }, dice: [{ x: 2, z: 0, top: 3, north: 2 }, { x: 3, z: 0, top: 3, north: 2 }, { x: 1, z: 1, top: 3, north: 2 }, { x: 0, z: 2, top: 3, north: 2 }, { x: 3, z: 2, top: 4, north: 5 }, { x: 0, z: 3, top: 3, north: 1 }] } },
  { id: 'P19', chapter: 0, seed: 30369, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['0,2,S', '0,3,E', '2,1,S,p', '3,1,S,p'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 2, z: 1, top: 3, north: 5 }, { x: 3, z: 1, top: 3, north: 5 }, { x: 0, z: 2, top: 6, north: 2 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 2, z: 3, top: 3, north: 2 }, { x: 3, z: 3, top: 3, north: 6 }] } },
  { id: 'P20', chapter: 0, seed: 30220, size: 4, values: [3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['3,3,N', '1,0,S', '1,1,S', '2,0,S', '3,0,W', '2,3,E'], layout: { start: { x: 3, z: 3 }, dice: [{ x: 1, z: 0, top: 4, north: 1 }, { x: 2, z: 0, top: 5, north: 3 }, { x: 3, z: 0, top: 6, north: 5 }, { x: 3, z: 1, top: 3, north: 2 }, { x: 2, z: 2, top: 3, north: 2 }, { x: 2, z: 3, top: 6, north: 2 }, { x: 3, z: 3, top: 5, north: 4 }] } },
  { id: 'P20', chapter: 0, seed: 30054, size: 4, values: [3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['1,0,S', '3,3,W', '2,2,W', '2,3,N', '3,2,N', '1,3,N'], layout: { start: { x: 3, z: 2 }, dice: [{ x: 1, z: 0, top: 5, north: 3 }, { x: 2, z: 0, top: 3, north: 6 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 2, z: 2, top: 6, north: 5 }, { x: 3, z: 2, top: 5, north: 4 }, { x: 1, z: 3, top: 2, north: 4 }, { x: 3, z: 3, top: 2, north: 4 }] } },
];
