import type { LevelSpec } from '../rules/types';

/**
 * The levels of the game: a ladder in chapters, and the game's lessons at once. Every level is a
 * board to clear, given die by die: nothing comes to it. Only the faces a level names work on it,
 * and a die that has joined a combo goes in two moves. A level is lost at a dead end: too few
 * dice standing for a combo with nothing going, or, where its floor is shut, the player left
 * with no move. As it is kept here a level has no limit of moves; played, it has the generous
 * one of its chapter, laid on it by `progress.ts`, which also rates a pass with stars and opens
 * the chapters.
 *
 * The ladder begins with the course, nine levels in three blocks: a combo, a step, two combos in
 * a row. A chapter of nine follows that brings two ways to read a die. In both the face that
 * works changes from level to level, the floor is shut, and the first level of a block says its
 * rule in a line (`lesson`) and shows its first move (`guide`). After them come the levels of the
 * ladder as it was, in three chapters by their faces, the ones most often cleared first; three of
 * them say the line of a rule until the chapters that are to teach it are made.
 *
 * The boards are not drawn by hand. They are picked by `node scripts/ladder.mjs chapter=N` among
 * the boards laid by the recipe of each place (`recipes.ts`): solved to the fewest moves, played
 * by the players made of the rules, kept when what they come to is what the place asks for, and
 * put together so that a level is unlike the one before it. `seed` is the seed the board was
 * laid from, kept for the record: a level is its dice. A seed above ten thousand is a board laid
 * from its solution, any other one laid at random. `solution` is a way of `par` moves, and the
 * test of this list plays it.
 */
export const LEVELS: readonly LevelSpec[] = [
  // The course.
  { id: 'T01', chapter: 0, seed: 78, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineCombo', guide: true, arrow: 'S', par: 1, exact: true, solution: ['1,0,S'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 2, z: 2, top: 3, north: 2 }, { x: 1, z: 2, top: 3, north: 2 }, { x: 1, z: 0, top: 6, north: 3 }] } },
  { id: 'T02', chapter: 0, seed: 113, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['1,0,E'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 2, z: 1, top: 2, north: 6 }, { x: 1, z: 0, top: 3, north: 6 }] } },
  { id: 'T03', chapter: 0, seed: 88, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['2,1,W'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 2, top: 4, north: 2 }, { x: 1, z: 2, top: 4, north: 6 }, { x: 0, z: 2, top: 4, north: 1 }, { x: 2, z: 1, top: 2, north: 1 }] } },
  { id: 'T04', chapter: 0, seed: 85, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineStep', guide: true, par: 1, exact: true, solution: ['0,1,S'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 1, z: 1, top: 3, north: 1 }, { x: 1, z: 2, top: 3, north: 6 }, { x: 0, z: 1, top: 5, north: 3 }] } },
  { id: 'T05', chapter: 0, seed: 218, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['1,1,E'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 1, z: 2, top: 4, north: 5 }, { x: 0, z: 2, top: 4, north: 2 }, { x: 2, z: 2, top: 4, north: 1 }, { x: 1, z: 1, top: 2, north: 6 }] } },
  { id: 'T06', chapter: 0, seed: 1086, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['0,1,E', '0,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 1, top: 6, north: 2 }, { x: 0, z: 2, top: 5, north: 4 }, { x: 1, z: 2, top: 3, north: 2 }] } },
  { id: 'T07', chapter: 0, seed: 10024, size: 3, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineWalk', until: 'end', guide: true, par: 2, exact: true, solution: ['1,1,N', '2,1,S'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 0, top: 2, north: 4 }, { x: 1, z: 1, top: 4, north: 5 }, { x: 2, z: 1, top: 4, north: 2 }, { x: 1, z: 2, top: 2, north: 4 }] } },
  { id: 'T08', chapter: 0, seed: 10013, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,2,E', '1,3,N'], layout: { start: { x: 1, z: 3 }, dice: [{ x: 0, z: 2, top: 3, north: 2 }, { x: 2, z: 2, top: 2, north: 1 }, { x: 0, z: 3, top: 3, north: 2 }, { x: 1, z: 3, top: 2, north: 4 }, { x: 2, z: 3, top: 3, north: 5 }, { x: 3, z: 3, top: 3, north: 1 }] } },
  { id: 'T09', chapter: 0, seed: 10874, size: 4, values: [2], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['1,1,N', '1,2,S', '1,3,W', '0,1,E'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 0, top: 2, north: 1 }, { x: 0, z: 1, top: 6, north: 4 }, { x: 1, z: 1, top: 4, north: 5 }, { x: 2, z: 1, top: 2, north: 6 }, { x: 0, z: 2, top: 2, north: 4 }, { x: 1, z: 2, top: 4, north: 6 }] } },
  // I. The faces of a die.
  { id: 'C101', chapter: 1, seed: 46, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSide', until: 'combo', guide: true, par: 2, exact: true, solution: ['0,2,E', '1,2,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 2, z: 2, top: 3, north: 5 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 0, z: 2, top: 6, north: 4 }] } },
  { id: 'C102', chapter: 1, seed: 174, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,2,N', '2,1,W'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 1, z: 0, top: 2, north: 6 }, { x: 2, z: 2, top: 4, north: 6 }] } },
  { id: 'C103', chapter: 1, seed: 10598, size: 4, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['0,1,E', '1,1,E', '2,1,N'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 3, z: 0, top: 4, north: 6 }, { x: 0, z: 1, top: 5, north: 3 }, { x: 3, z: 1, top: 4, north: 5 }, { x: 3, z: 2, top: 4, north: 6 }] } },
  { id: 'C104', chapter: 1, seed: 10299, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['2,3,E', '3,3,N', '1,1,W'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 0, z: 0, top: 3, north: 5 }, { x: 1, z: 0, top: 3, north: 1 }, { x: 1, z: 1, top: 5, north: 1 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 2, z: 2, top: 3, north: 6 }, { x: 2, z: 3, top: 5, north: 4 }] } },
  { id: 'C105', chapter: 1, seed: 105, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSeven', until: 'combo', guide: true, par: 2, exact: true, solution: ['0,2,N', '0,1,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 1, z: 0, top: 3, north: 5 }, { x: 1, z: 1, top: 3, north: 6 }, { x: 0, z: 2, top: 4, north: 6 }] } },
  { id: 'C106', chapter: 1, seed: 907, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,0,S', '2,1,S'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 2, z: 0, top: 5, north: 6 }, { x: 1, z: 2, top: 2, north: 3 }] } },
  { id: 'C107', chapter: 1, seed: 191, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['2,3,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 0, z: 3, top: 5, north: 3 }, { x: 1, z: 3, top: 5, north: 6 }, { x: 0, z: 2, top: 5, north: 1 }, { x: 1, z: 2, top: 5, north: 3 }, { x: 2, z: 3, top: 3, north: 2 }] } },
  { id: 'C108', chapter: 1, seed: 18, size: 4, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['3,0,S', '3,1,S', '2,1,E', '3,1,N'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 2, z: 0, top: 2, north: 4 }, { x: 2, z: 1, top: 6, north: 5 }, { x: 3, z: 0, top: 5, north: 1 }, { x: 2, z: 2, top: 2, north: 6 }] } },
  { id: 'C109', chapter: 1, seed: 10880, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['1,2,E', '3,1,S', '3,2,S', '3,3,W'], layout: { start: { x: 0, z: 3 }, dice: [{ x: 1, z: 1, top: 3, north: 6 }, { x: 2, z: 1, top: 3, north: 5 }, { x: 3, z: 1, top: 6, north: 5 }, { x: 1, z: 2, top: 5, north: 6 }, { x: 0, z: 3, top: 3, north: 1 }, { x: 1, z: 3, top: 3, north: 1 }] } },
  // The ladder as it was. 3s.
  { id: 'B05', chapter: 5, seed: 10588, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lineLink', par: 4, exact: true, solution: ['3,1,W', '1,0,W', '3,0,S', '2,0,W'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 1, z: 0, top: 5, north: 1 }, { x: 2, z: 0, top: 6, north: 5 }, { x: 3, z: 0, top: 2, north: 3 }, { x: 0, z: 1, top: 3, north: 5 }, { x: 1, z: 1, top: 3, north: 1 }, { x: 3, z: 1, top: 5, north: 1 }] } },
  { id: 'B13', chapter: 5, seed: 36, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lineFloor', par: 5, exact: true, solution: ['2,0,S', '3,0,S', '3,1,S', '1,0,E,p', '1,3,N'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 3, z: 0, top: 4, north: 5 }, { x: 2, z: 0, top: 2, north: 3 }, { x: 2, z: 2, top: 3, north: 5 }, { x: 1, z: 0, top: 3, north: 6 }, { x: 1, z: 3, top: 2, north: 4 }, { x: 3, z: 1, top: 3, north: 6 }] } },
  { id: 'B14', chapter: 5, seed: 10436, size: 3, values: [3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 7, exact: true, solution: ['0,1,E', '0,2,N', '0,1,N', '1,2,N', '2,2,W', '2,1,S', '1,1,E'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 0, top: 3, north: 6 }, { x: 2, z: 0, top: 3, north: 5 }, { x: 0, z: 1, top: 6, north: 2 }, { x: 2, z: 1, top: 2, north: 3 }, { x: 0, z: 2, top: 4, north: 2 }, { x: 1, z: 2, top: 6, north: 2 }, { x: 2, z: 2, top: 5, north: 1 }] } },
  { id: 'B06', chapter: 5, seed: 10148, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['2,1,W', '2,3,W', '2,2,S', '1,2,E', '3,3,N', '3,1,W'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 2, z: 1, top: 6, north: 5 }, { x: 3, z: 1, top: 5, north: 1 }, { x: 1, z: 2, top: 5, north: 6 }, { x: 2, z: 2, top: 2, north: 3 }, { x: 2, z: 3, top: 6, north: 5 }, { x: 3, z: 3, top: 6, north: 4 }] } },
  { id: 'B08', chapter: 5, seed: 108, size: 4, values: [3], norm: 9, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['1,2,E', '1,1,S', '1,0,S', '2,0,W', '1,0,W', '0,2,N', '1,2,W', '2,2,W'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 0, top: 3, north: 1 }, { x: 1, z: 0, top: 2, north: 3 }, { x: 0, z: 1, top: 3, north: 1 }, { x: 1, z: 1, top: 6, north: 5 }, { x: 2, z: 1, top: 3, north: 1 }, { x: 1, z: 2, top: 3, north: 5 }, { x: 0, z: 2, top: 5, north: 4 }, { x: 2, z: 0, top: 4, north: 5 }, { x: 0, z: 3, top: 3, north: 5 }] } },
  { id: 'B07', chapter: 5, seed: 10352, size: 3, values: [3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['2,0,W', '0,1,S', '1,1,W', '1,2,N', '0,0,E', '1,0,E'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 0, z: 0, top: 4, north: 5 }, { x: 2, z: 0, top: 5, north: 1 }, { x: 0, z: 1, top: 6, north: 3 }, { x: 1, z: 1, top: 2, north: 6 }, { x: 2, z: 1, top: 3, north: 1 }, { x: 1, z: 2, top: 5, north: 4 }, { x: 2, z: 2, top: 3, north: 2 }] } },
  // 2s and 3s.
  { id: 'B11', chapter: 6, seed: 309, size: 4, values: [2, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, lesson: 'lineFaces', par: 4, exact: true, solution: ['1,2,W', '1,1,E', '2,2,W', '0,1,S'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 1, z: 1, top: 2, north: 1 }, { x: 1, z: 0, top: 3, north: 2 }, { x: 1, z: 2, top: 4, north: 6 }, { x: 2, z: 0, top: 3, north: 6 }, { x: 2, z: 2, top: 4, north: 6 }, { x: 0, z: 1, top: 3, north: 2 }] } },
  { id: 'B15', chapter: 6, seed: 10063, size: 5, values: [2, 3], norm: 9, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['4,0,W', '3,1,N', '0,1,N', '2,4,E,p', '4,4,N', '3,4,E', '3,3,E', '4,1,S'], layout: { start: { x: 4, z: 1 }, dice: [{ x: 1, z: 0, top: 3, north: 5 }, { x: 2, z: 0, top: 3, north: 2 }, { x: 4, z: 0, top: 6, north: 5 }, { x: 0, z: 1, top: 5, north: 4 }, { x: 3, z: 1, top: 6, north: 4 }, { x: 4, z: 1, top: 6, north: 2 }, { x: 3, z: 3, top: 6, north: 4 }, { x: 2, z: 4, top: 3, north: 6 }, { x: 4, z: 4, top: 4, north: 5 }] } },
  { id: 'B10', chapter: 6, seed: 745, size: 3, values: [2, 3], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['1,2,W', '1,1,S', '1,2,E', '2,0,W', '1,0,S'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 1, z: 2, top: 3, north: 1 }, { x: 1, z: 1, top: 5, north: 6 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 2, z: 0, top: 6, north: 3 }, { x: 0, z: 1, top: 2, north: 1 }] } },
  { id: 'B16', chapter: 6, seed: 68, size: 4, values: [2, 3], norm: 10, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['1,1,W', '1,0,S', '0,0,E', '1,1,E', '1,2,W', '3,2,N', '1,0,S', '1,1,E'], layout: { start: { x: 3, z: 2 }, dice: [{ x: 1, z: 0, top: 5, north: 6 }, { x: 0, z: 3, top: 3, north: 5 }, { x: 2, z: 0, top: 2, north: 6 }, { x: 0, z: 0, top: 5, north: 4 }, { x: 3, z: 2, top: 6, north: 4 }, { x: 3, z: 1, top: 3, north: 2 }, { x: 1, z: 1, top: 5, north: 1 }, { x: 3, z: 0, top: 3, north: 1 }, { x: 2, z: 2, top: 3, north: 1 }, { x: 1, z: 2, top: 5, north: 1 }] } },
  { id: 'B12', chapter: 6, seed: 412, size: 4, values: [2, 3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['1,0,S', '2,0,W', '1,3,N', '3,3,N', '1,2,E', '2,2,E'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 2, z: 2, top: 3, north: 1 }, { x: 2, z: 1, top: 2, north: 1 }, { x: 2, z: 3, top: 3, north: 6 }, { x: 3, z: 3, top: 6, north: 4 }, { x: 1, z: 3, top: 6, north: 3 }, { x: 2, z: 0, top: 3, north: 1 }, { x: 1, z: 0, top: 6, north: 2 }] } },
  // 5s.
  { id: 'B20', chapter: 7, seed: 10570, size: 5, values: [5], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['2,0,E', '3,0,S', '3,1,E', '4,1,S', '4,2,W', '2,4,E'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 2, z: 0, top: 3, north: 5 }, { x: 3, z: 3, top: 5, north: 6 }, { x: 4, z: 3, top: 5, north: 6 }, { x: 2, z: 4, top: 6, north: 3 }, { x: 3, z: 4, top: 5, north: 4 }, { x: 4, z: 4, top: 5, north: 3 }] } },
  { id: 'B19', chapter: 7, seed: 176, size: 4, values: [5], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,1,N', '1,0,E', '2,0,E', '2,3,E'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 3, z: 3, top: 5, north: 6 }, { x: 2, z: 3, top: 3, north: 1 }, { x: 3, z: 2, top: 5, north: 4 }, { x: 3, z: 1, top: 5, north: 3 }, { x: 2, z: 1, top: 5, north: 1 }, { x: 1, z: 1, top: 6, north: 5 }] } },
  { id: 'B21', chapter: 7, seed: 87, size: 4, values: [5], norm: 8, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['1,1,W', '0,1,S', '0,2,E', '1,2,N', '1,1,E', '3,1,S'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 2, z: 0, top: 5, north: 1 }, { x: 3, z: 0, top: 5, north: 3 }, { x: 3, z: 1, top: 4, north: 5 }, { x: 1, z: 0, top: 5, north: 4 }, { x: 3, z: 2, top: 5, north: 3 }, { x: 0, z: 0, top: 5, north: 6 }, { x: 2, z: 2, top: 5, north: 1 }, { x: 1, z: 1, top: 3, north: 2 }] } },
];

/**
 * Boards in reserve. For a place of the course or of the first chapter, the boards that fit it
 * next best; for a place of the ladder as it was, the two that did, and the nine levels of that
 * ladder that the course has taken the place of or that no player made of the rules clears.
 * They take a level's place when playtests ask for another.
 */
export const SPARES: readonly LevelSpec[] = [
  { id: 'T01', chapter: 0, seed: 118, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineCombo', guide: true, arrow: 'S', par: 1, exact: true, solution: ['1,0,S'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 0, z: 2, top: 3, north: 5 }, { x: 1, z: 2, top: 3, north: 6 }, { x: 1, z: 0, top: 6, north: 3 }] } },
  { id: 'T01', chapter: 0, seed: 214, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineCombo', guide: true, arrow: 'N', par: 1, exact: true, solution: ['0,2,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 0, z: 0, top: 3, north: 2 }, { x: 1, z: 0, top: 3, north: 5 }, { x: 0, z: 2, top: 5, north: 4 }] } },
  { id: 'T01', chapter: 0, seed: 356, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineCombo', guide: true, arrow: 'S', par: 1, exact: true, solution: ['2,0,S'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 1, z: 2, top: 3, north: 6 }, { x: 2, z: 2, top: 3, north: 6 }, { x: 2, z: 0, top: 5, north: 3 }] } },
  { id: 'T01', chapter: 0, seed: 371, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineCombo', guide: true, arrow: 'W', par: 1, exact: true, solution: ['1,2,W'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 1, top: 3, north: 1 }, { x: 1, z: 1, top: 3, north: 5 }, { x: 1, z: 2, top: 6, north: 5 }] } },
  { id: 'T02', chapter: 0, seed: 405, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['2,0,W'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 2, z: 0, top: 4, north: 6 }, { x: 1, z: 1, top: 2, north: 1 }] } },
  { id: 'T02', chapter: 0, seed: 535, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['1,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 2, top: 6, north: 5 }, { x: 0, z: 1, top: 2, north: 3 }] } },
  { id: 'T02', chapter: 0, seed: 684, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['0,2,E'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 0, z: 2, top: 3, north: 6 }, { x: 1, z: 1, top: 2, north: 1 }] } },
  { id: 'T02', chapter: 0, seed: 825, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['2,0,W'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 2, z: 0, top: 4, north: 6 }, { x: 1, z: 1, top: 2, north: 4 }] } },
  { id: 'T03', chapter: 0, seed: 133, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['1,0,S'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 0, z: 0, top: 4, north: 1 }, { x: 0, z: 1, top: 4, north: 1 }, { x: 0, z: 2, top: 4, north: 1 }, { x: 1, z: 0, top: 5, north: 4 }] } },
  { id: 'T03', chapter: 0, seed: 171, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['1,2,W'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 1, top: 4, north: 6 }, { x: 0, z: 1, top: 4, north: 2 }, { x: 0, z: 0, top: 4, north: 2 }, { x: 1, z: 2, top: 5, north: 6 }] } },
  { id: 'T03', chapter: 0, seed: 276, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['1,0,E'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 1, z: 1, top: 4, north: 6 }, { x: 2, z: 1, top: 4, north: 2 }, { x: 1, z: 2, top: 4, north: 2 }, { x: 1, z: 0, top: 2, north: 6 }] } },
  { id: 'T03', chapter: 0, seed: 417, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['1,1,E'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 2, z: 2, top: 4, north: 1 }, { x: 1, z: 2, top: 4, north: 2 }, { x: 0, z: 2, top: 4, north: 5 }, { x: 1, z: 1, top: 2, north: 6 }] } },
  { id: 'T04', chapter: 0, seed: 93, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineStep', guide: true, par: 1, exact: true, solution: ['1,0,S'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 0, top: 3, north: 2 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 1, z: 0, top: 6, north: 3 }] } },
  { id: 'T04', chapter: 0, seed: 121, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineStep', guide: true, par: 1, exact: true, solution: ['1,2,W'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 1, z: 1, top: 3, north: 5 }, { x: 0, z: 1, top: 3, north: 6 }, { x: 1, z: 2, top: 5, north: 1 }] } },
  { id: 'T04', chapter: 0, seed: 246, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineStep', guide: true, par: 1, exact: true, solution: ['1,0,S'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 0, z: 0, top: 3, north: 2 }, { x: 0, z: 1, top: 3, north: 2 }, { x: 1, z: 0, top: 2, north: 3 }] } },
  { id: 'T04', chapter: 0, seed: 272, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineStep', guide: true, par: 1, exact: true, solution: ['2,2,W'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 2, z: 1, top: 3, north: 5 }, { x: 1, z: 1, top: 3, north: 1 }, { x: 2, z: 2, top: 6, north: 5 }] } },
  { id: 'T05', chapter: 0, seed: 329, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['0,1,S'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 1, z: 1, top: 4, north: 6 }, { x: 1, z: 2, top: 4, north: 5 }, { x: 2, z: 2, top: 4, north: 5 }, { x: 0, z: 1, top: 6, north: 4 }] } },
  { id: 'T05', chapter: 0, seed: 442, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['1,0,W'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 0, z: 2, top: 4, north: 2 }, { x: 0, z: 1, top: 4, north: 5 }, { x: 1, z: 1, top: 4, north: 5 }, { x: 1, z: 0, top: 6, north: 2 }] } },
  { id: 'T05', chapter: 0, seed: 748, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['0,1,E'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 2, top: 4, north: 2 }, { x: 1, z: 2, top: 4, north: 2 }, { x: 2, z: 2, top: 4, north: 2 }, { x: 0, z: 1, top: 6, north: 5 }] } },
  { id: 'T05', chapter: 0, seed: 889, size: 3, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['1,1,E'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 1, z: 2, top: 4, north: 6 }, { x: 0, z: 2, top: 4, north: 1 }, { x: 2, z: 2, top: 4, north: 2 }, { x: 1, z: 1, top: 2, north: 6 }] } },
  { id: 'T06', chapter: 0, seed: 1114, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,1,W', '2,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 2, top: 3, north: 6 }, { x: 2, z: 2, top: 5, north: 4 }, { x: 2, z: 1, top: 5, north: 1 }] } },
  { id: 'T06', chapter: 0, seed: 1447, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['0,1,E', '0,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 2, top: 6, north: 4 }, { x: 0, z: 1, top: 5, north: 6 }, { x: 1, z: 2, top: 3, north: 6 }] } },
  { id: 'T06', chapter: 0, seed: 10420, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,1,W', '2,2,N'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 1, top: 2, north: 6 }, { x: 1, z: 2, top: 3, north: 5 }, { x: 2, z: 2, top: 6, north: 4 }] } },
  { id: 'T07', chapter: 0, seed: 10038, size: 3, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineWalk', until: 'end', guide: true, par: 2, exact: true, solution: ['1,1,E', '1,2,W'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 0, z: 1, top: 2, north: 6 }, { x: 1, z: 1, top: 6, north: 4 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 2, z: 2, top: 2, north: 4 }] } },
  { id: 'T07', chapter: 0, seed: 10039, size: 3, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineWalk', until: 'end', guide: true, par: 2, exact: true, solution: ['1,1,E', '1,2,W'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 1, top: 2, north: 6 }, { x: 1, z: 1, top: 3, north: 6 }, { x: 1, z: 2, top: 4, north: 6 }, { x: 2, z: 2, top: 2, north: 6 }] } },
  { id: 'T07', chapter: 0, seed: 10046, size: 3, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineWalk', until: 'end', guide: true, par: 2, exact: true, solution: ['1,1,E', '1,2,W'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 1, top: 2, north: 6 }, { x: 1, z: 1, top: 3, north: 6 }, { x: 1, z: 2, top: 6, north: 3 }, { x: 2, z: 2, top: 2, north: 3 }] } },
  { id: 'T07', chapter: 0, seed: 10050, size: 3, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineWalk', until: 'end', guide: true, par: 2, exact: true, solution: ['1,1,E', '1,2,W'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 1, top: 2, north: 1 }, { x: 1, z: 1, top: 4, north: 1 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 2, z: 2, top: 2, north: 6 }] } },
  { id: 'T08', chapter: 0, seed: 10053, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['3,0,S', '2,1,W'], layout: { start: { x: 3, z: 2 }, dice: [{ x: 1, z: 0, top: 3, north: 5 }, { x: 2, z: 0, top: 3, north: 2 }, { x: 3, z: 0, top: 2, north: 3 }, { x: 2, z: 1, top: 2, north: 6 }, { x: 2, z: 2, top: 3, north: 5 }, { x: 3, z: 2, top: 3, north: 5 }] } },
  { id: 'T08', chapter: 0, seed: 10153, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['1,2,W', '2,3,N'], layout: { start: { x: 3, z: 2 }, dice: [{ x: 1, z: 2, top: 5, north: 1 }, { x: 3, z: 2, top: 3, north: 6 }, { x: 0, z: 3, top: 3, north: 1 }, { x: 1, z: 3, top: 3, north: 2 }, { x: 2, z: 3, top: 6, north: 4 }, { x: 3, z: 3, top: 3, north: 1 }] } },
  { id: 'T08', chapter: 0, seed: 10335, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,2,E', '1,3,N'], layout: { start: { x: 3, z: 3 }, dice: [{ x: 0, z: 2, top: 3, north: 2 }, { x: 2, z: 2, top: 5, north: 6 }, { x: 0, z: 3, top: 3, north: 1 }, { x: 1, z: 3, top: 6, north: 4 }, { x: 2, z: 3, top: 3, north: 5 }, { x: 3, z: 3, top: 3, north: 1 }] } },
  { id: 'T08', chapter: 0, seed: 10669, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['1,2,W', '2,3,N'], layout: { start: { x: 3, z: 2 }, dice: [{ x: 1, z: 2, top: 5, north: 1 }, { x: 3, z: 2, top: 3, north: 6 }, { x: 0, z: 3, top: 3, north: 5 }, { x: 1, z: 3, top: 3, north: 5 }, { x: 2, z: 3, top: 5, north: 4 }, { x: 3, z: 3, top: 3, north: 2 }] } },
  { id: 'T09', chapter: 0, seed: 10606, size: 4, values: [2], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['1,0,W', '0,2,S', '0,3,E', '1,1,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 1, z: 0, top: 3, north: 1 }, { x: 2, z: 0, top: 2, north: 6 }, { x: 0, z: 1, top: 2, north: 1 }, { x: 1, z: 1, top: 6, north: 5 }, { x: 0, z: 2, top: 3, north: 6 }, { x: 1, z: 2, top: 2, north: 3 }] } },
  { id: 'T09', chapter: 0, seed: 10636, size: 4, values: [2], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['3,1,S', '1,0,W', '0,0,S', '2,1,E'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 1, z: 0, top: 4, north: 2 }, { x: 3, z: 0, top: 2, north: 1 }, { x: 1, z: 1, top: 2, north: 6 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 3, z: 1, top: 6, north: 2 }, { x: 2, z: 2, top: 2, north: 4 }] } },
  { id: 'T09', chapter: 0, seed: 10607, size: 4, values: [2], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['0,2,N', '2,3,E', '3,3,N', '1,2,W'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 1, z: 1, top: 2, north: 6 }, { x: 0, z: 2, top: 6, north: 5 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 2, z: 2, top: 2, north: 1 }, { x: 0, z: 3, top: 2, north: 1 }, { x: 2, z: 3, top: 6, north: 5 }] } },
  { id: 'T09', chapter: 0, seed: 10973, size: 4, values: [2], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['2,2,S', '0,1,N', '0,0,E', '1,2,E'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 1, top: 3, north: 6 }, { x: 1, z: 1, top: 2, north: 1 }, { x: 1, z: 2, top: 3, north: 6 }, { x: 2, z: 2, top: 6, north: 2 }, { x: 3, z: 2, top: 2, north: 3 }, { x: 1, z: 3, top: 2, north: 1 }] } },
  { id: 'C101', chapter: 1, seed: 72, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSide', until: 'combo', guide: true, par: 2, exact: true, solution: ['2,2,W', '1,2,N'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 0, z: 2, top: 3, north: 2 }, { x: 0, z: 1, top: 3, north: 6 }, { x: 2, z: 2, top: 6, north: 4 }] } },
  { id: 'C101', chapter: 1, seed: 152, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSide', until: 'combo', guide: true, par: 2, exact: true, solution: ['0,2,E', '1,2,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 2, z: 0, top: 3, north: 1 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 0, z: 2, top: 2, north: 4 }] } },
  { id: 'C101', chapter: 1, seed: 544, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSide', until: 'combo', guide: true, par: 2, exact: true, solution: ['0,1,E', '1,1,N'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 2, z: 0, top: 3, north: 6 }, { x: 2, z: 1, top: 3, north: 5 }, { x: 0, z: 1, top: 5, north: 4 }] } },
  { id: 'C101', chapter: 1, seed: 583, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSide', until: 'combo', guide: true, par: 2, exact: true, solution: ['0,1,E', '1,1,N'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 2, z: 0, top: 3, north: 2 }, { x: 2, z: 1, top: 3, north: 1 }, { x: 0, z: 1, top: 2, north: 4 }] } },
  { id: 'C102', chapter: 1, seed: 537, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,2,N', '2,1,W'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 2, z: 2, top: 4, north: 6 }, { x: 1, z: 0, top: 2, north: 1 }] } },
  { id: 'C102', chapter: 1, seed: 690, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['0,2,N', '0,1,E'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 1, z: 0, top: 2, north: 4 }, { x: 0, z: 2, top: 3, north: 6 }] } },
  { id: 'C102', chapter: 1, seed: 876, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,2,W', '1,2,N'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 1, z: 0, top: 2, north: 6 }, { x: 2, z: 2, top: 4, north: 5 }] } },
  { id: 'C102', chapter: 1, seed: 933, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['0,2,N', '0,1,E'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 1, z: 0, top: 2, north: 6 }, { x: 0, z: 2, top: 3, north: 6 }] } },
  { id: 'C103', chapter: 1, seed: 829, size: 4, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['0,0,S', '0,1,S', '0,2,E'], layout: { start: { x: 0, z: 0 }, dice: [{ x: 2, z: 3, top: 4, north: 6 }, { x: 1, z: 3, top: 4, north: 1 }, { x: 3, z: 3, top: 4, north: 1 }, { x: 0, z: 0, top: 2, north: 6 }] } },
  { id: 'C103', chapter: 1, seed: 11119, size: 4, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['2,3,N', '2,2,N', '2,1,W'], layout: { start: { x: 2, z: 3 }, dice: [{ x: 1, z: 0, top: 4, north: 5 }, { x: 2, z: 0, top: 4, north: 1 }, { x: 3, z: 0, top: 4, north: 5 }, { x: 2, z: 3, top: 5, north: 6 }] } },
  { id: 'C103', chapter: 1, seed: 11482, size: 4, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['1,3,N', '1,2,N', '1,1,E'], layout: { start: { x: 1, z: 3 }, dice: [{ x: 1, z: 0, top: 4, north: 5 }, { x: 2, z: 0, top: 4, north: 5 }, { x: 3, z: 0, top: 4, north: 6 }, { x: 1, z: 3, top: 5, north: 1 }] } },
  { id: 'C103', chapter: 1, seed: 11246, size: 4, values: [4], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [4], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['0,3,E', '1,3,E', '2,3,N'], layout: { start: { x: 0, z: 3 }, dice: [{ x: 3, z: 1, top: 4, north: 5 }, { x: 3, z: 2, top: 4, north: 1 }, { x: 0, z: 3, top: 6, north: 3 }, { x: 3, z: 3, top: 4, north: 2 }] } },
  { id: 'C104', chapter: 1, seed: 10486, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['1,2,W', '1,3,N', '2,2,S'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 1, z: 2, top: 5, north: 1 }, { x: 2, z: 2, top: 5, north: 3 }, { x: 3, z: 2, top: 3, north: 5 }, { x: 0, z: 3, top: 3, north: 5 }, { x: 1, z: 3, top: 6, north: 4 }, { x: 3, z: 3, top: 3, north: 1 }] } },
  { id: 'C104', chapter: 1, seed: 10476, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['1,0,E', '2,0,S', '2,2,S'], layout: { start: { x: 3, z: 2 }, dice: [{ x: 1, z: 0, top: 2, north: 3 }, { x: 1, z: 1, top: 3, north: 1 }, { x: 1, z: 2, top: 3, north: 2 }, { x: 2, z: 2, top: 2, north: 3 }, { x: 3, z: 2, top: 3, north: 1 }, { x: 3, z: 3, top: 3, north: 6 }] } },
  { id: 'C104', chapter: 1, seed: 10945, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['3,2,N', '3,1,W', '1,1,N'], layout: { start: { x: 3, z: 2 }, dice: [{ x: 0, z: 0, top: 3, north: 6 }, { x: 0, z: 1, top: 3, north: 5 }, { x: 1, z: 1, top: 5, north: 4 }, { x: 1, z: 2, top: 3, north: 6 }, { x: 2, z: 2, top: 3, north: 6 }, { x: 3, z: 2, top: 2, north: 6 }] } },
  { id: 'C104', chapter: 1, seed: 11206, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 3, exact: true, solution: ['3,2,N', '3,1,W', '1,1,N'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 0, z: 0, top: 3, north: 1 }, { x: 0, z: 1, top: 3, north: 2 }, { x: 1, z: 1, top: 6, north: 4 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 2, z: 2, top: 3, north: 5 }, { x: 3, z: 2, top: 5, north: 1 }] } },
  { id: 'C105', chapter: 1, seed: 131, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSeven', until: 'combo', guide: true, par: 2, exact: true, solution: ['2,0,S', '2,1,S'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 0, z: 2, top: 3, north: 1 }, { x: 1, z: 2, top: 3, north: 6 }, { x: 2, z: 0, top: 4, north: 1 }] } },
  { id: 'C105', chapter: 1, seed: 334, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSeven', until: 'combo', guide: true, par: 2, exact: true, solution: ['2,0,S', '2,1,S'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 1, z: 1, top: 3, north: 6 }, { x: 1, z: 2, top: 3, north: 5 }, { x: 2, z: 0, top: 4, north: 2 }] } },
  { id: 'C105', chapter: 1, seed: 344, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSeven', until: 'combo', guide: true, par: 2, exact: true, solution: ['0,2,E', '1,2,E'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 1, z: 1, top: 3, north: 5 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 0, z: 2, top: 4, north: 1 }] } },
  { id: 'C105', chapter: 1, seed: 425, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, lesson: 'lineSeven', until: 'combo', guide: true, par: 2, exact: true, solution: ['1,0,S', '1,1,S'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 2, z: 1, top: 3, north: 2 }, { x: 2, z: 2, top: 3, north: 5 }, { x: 1, z: 0, top: 4, north: 6 }] } },
  { id: 'C106', chapter: 1, seed: 1143, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,0,S', '2,1,S'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 1, z: 2, top: 2, north: 6 }, { x: 2, z: 0, top: 5, north: 4 }] } },
  { id: 'C106', chapter: 1, seed: 1157, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,0,S', '2,1,S'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 2, z: 0, top: 5, north: 4 }, { x: 1, z: 2, top: 2, north: 3 }] } },
  { id: 'C106', chapter: 1, seed: 10007, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,0,S', '2,1,S'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 2, z: 0, top: 5, north: 1 }, { x: 1, z: 2, top: 2, north: 4 }] } },
  { id: 'C106', chapter: 1, seed: 10043, size: 3, values: [2], norm: 2, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 2, exact: true, solution: ['2,0,S', '2,1,S'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 2, z: 0, top: 5, north: 4 }, { x: 1, z: 2, top: 2, north: 4 }] } },
  { id: 'C107', chapter: 1, seed: 304, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['2,3,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 0, z: 3, top: 5, north: 3 }, { x: 0, z: 2, top: 5, north: 1 }, { x: 1, z: 3, top: 5, north: 6 }, { x: 1, z: 2, top: 5, north: 6 }, { x: 2, z: 3, top: 3, north: 2 }] } },
  { id: 'C107', chapter: 1, seed: 311, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['2,2,E'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 1, top: 5, north: 1 }, { x: 2, z: 0, top: 5, north: 4 }, { x: 1, z: 0, top: 5, north: 3 }, { x: 3, z: 1, top: 5, north: 4 }, { x: 2, z: 2, top: 3, north: 1 }] } },
  { id: 'C107', chapter: 1, seed: 440, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['2,2,E'], layout: { start: { x: 1, z: 3 }, dice: [{ x: 3, z: 3, top: 5, north: 1 }, { x: 2, z: 3, top: 5, north: 3 }, { x: 1, z: 3, top: 5, north: 6 }, { x: 1, z: 2, top: 5, north: 6 }, { x: 2, z: 2, top: 3, north: 1 }] } },
  { id: 'C107', chapter: 1, seed: 481, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 1, exact: true, solution: ['2,2,S'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 1, z: 1, top: 5, north: 6 }, { x: 1, z: 2, top: 5, north: 1 }, { x: 1, z: 3, top: 5, north: 4 }, { x: 2, z: 1, top: 5, north: 4 }, { x: 2, z: 2, top: 3, north: 5 }] } },
  { id: 'C108', chapter: 1, seed: 10919, size: 4, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['2,0,S', '2,1,S', '1,1,E', '2,1,N'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 1, z: 0, top: 2, north: 3 }, { x: 2, z: 0, top: 5, north: 3 }, { x: 1, z: 1, top: 3, north: 5 }, { x: 1, z: 2, top: 2, north: 4 }] } },
  { id: 'C108', chapter: 1, seed: 11156, size: 4, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['1,0,E', '2,0,E', '2,1,N', '2,0,W'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 1, z: 0, top: 5, north: 1 }, { x: 1, z: 1, top: 2, north: 6 }, { x: 2, z: 1, top: 3, north: 1 }, { x: 3, z: 1, top: 2, north: 3 }] } },
  { id: 'C108', chapter: 1, seed: 10143, size: 4, values: [2], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['2,1,N', '2,0,E', '3,2,W', '2,2,W'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 1, z: 1, top: 2, north: 1 }, { x: 2, z: 1, top: 4, north: 1 }, { x: 3, z: 1, top: 2, north: 6 }, { x: 3, z: 2, top: 5, north: 6 }] } },
  { id: 'C109', chapter: 1, seed: 10370, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['3,1,W', '1,0,S', '1,1,S', '1,2,E'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 1, z: 0, top: 6, north: 2 }, { x: 2, z: 0, top: 3, north: 2 }, { x: 3, z: 0, top: 3, north: 2 }, { x: 3, z: 1, top: 2, north: 6 }, { x: 3, z: 2, top: 3, north: 6 }, { x: 3, z: 3, top: 3, north: 6 }] } },
  { id: 'C109', chapter: 1, seed: 10475, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['2,1,W', '0,2,N', '0,1,N', '0,0,E'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 0, top: 3, north: 5 }, { x: 3, z: 0, top: 3, north: 6 }, { x: 2, z: 1, top: 6, north: 5 }, { x: 0, z: 2, top: 5, north: 6 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 2, z: 2, top: 3, north: 1 }] } },
  { id: 'C109', chapter: 1, seed: 11006, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['2,1,N', '1,2,E', '2,2,S', '2,3,E'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 1, z: 0, top: 3, north: 1 }, { x: 1, z: 1, top: 3, north: 5 }, { x: 2, z: 1, top: 6, north: 4 }, { x: 3, z: 1, top: 3, north: 2 }, { x: 1, z: 2, top: 4, north: 6 }, { x: 3, z: 2, top: 3, north: 5 }] } },
  { id: 'C109', chapter: 1, seed: 11013, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, floor: false, guard: true, par: 4, exact: true, solution: ['1,2,N', '2,2,E', '1,1,S', '1,2,S'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 2, z: 1, top: 3, north: 2 }, { x: 3, z: 1, top: 3, north: 6 }, { x: 0, z: 2, top: 3, north: 1 }, { x: 1, z: 2, top: 5, north: 3 }, { x: 2, z: 2, top: 5, north: 6 }, { x: 0, z: 3, top: 3, north: 5 }] } },
  { id: 'B01', chapter: 5, seed: 290, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonThrees', arrow: 'N', par: 1, exact: true, solution: ['1,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 2, z: 2, top: 3, north: 2 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 1, z: 2, top: 2, north: 4 }] } },
  { id: 'B02', chapter: 5, seed: 10, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonStep', par: 3, exact: true, solution: ['1,2,E', '2,2,N', '2,1,N'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 1, z: 1, top: 3, north: 2 }, { x: 1, z: 2, top: 2, north: 6 }, { x: 1, z: 0, top: 3, north: 1 }] } },
  { id: 'B03', chapter: 5, seed: 368, size: 3, values: [3], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonLink', par: 3, exact: true, solution: ['0,0,S', '2,0,S', '1,0,W'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 1, z: 0, top: 6, north: 5 }, { x: 0, z: 0, top: 2, north: 3 }, { x: 1, z: 1, top: 3, north: 1 }, { x: 2, z: 0, top: 2, north: 3 }] } },
  { id: 'B04', chapter: 5, seed: 163, size: 3, values: [3], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonSeven', par: 4, exact: true, solution: ['1,2,E', '2,2,N', '0,2,E', '0,1,S'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 1, z: 1, top: 3, north: 6 }, { x: 1, z: 2, top: 6, north: 4 }, { x: 0, z: 2, top: 5, north: 6 }, { x: 0, z: 1, top: 2, north: 3 }] } },
  { id: 'B09', chapter: 6, seed: 10088, size: 3, values: [2, 3], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonTwos', par: 3, exact: true, solution: ['2,1,W', '2,2,N', '1,2,E'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 1, z: 0, top: 3, north: 1 }, { x: 2, z: 0, top: 3, north: 5 }, { x: 2, z: 1, top: 6, north: 5 }, { x: 1, z: 2, top: 6, north: 2 }, { x: 2, z: 2, top: 2, north: 4 }] } },
  { id: 'B17', chapter: 7, seed: 7, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, lesson: 'lessonFives', par: 1, exact: true, solution: ['0,1,S'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 1, z: 1, top: 5, north: 6 }, { x: 1, z: 0, top: 5, north: 1 }, { x: 0, z: 0, top: 5, north: 1 }, { x: 1, z: 2, top: 5, north: 6 }, { x: 0, z: 1, top: 3, north: 5 }] } },
  { id: 'B18', chapter: 7, seed: 5, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['3,1,N', '3,0,W', '2,0,S', '2,1,E'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 3, z: 2, top: 5, north: 1 }, { x: 3, z: 3, top: 5, north: 3 }, { x: 2, z: 2, top: 5, north: 6 }, { x: 2, z: 3, top: 5, north: 4 }, { x: 3, z: 1, top: 4, north: 2 }] } },
  { id: 'B22', chapter: 7, seed: 91, size: 5, values: [5], norm: 10, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['1,2,N', '2,0,S', '1,1,S', '3,3,N', '2,1,W', '3,0,W,p', '3,2,S,p', '3,3,N'], layout: { start: { x: 4, z: 3 }, dice: [{ x: 2, z: 2, top: 5, north: 6 }, { x: 4, z: 3, top: 5, north: 1 }, { x: 2, z: 3, top: 5, north: 4 }, { x: 2, z: 0, top: 4, north: 1 }, { x: 3, z: 3, top: 2, north: 1 }, { x: 4, z: 2, top: 5, north: 4 }, { x: 1, z: 2, top: 5, north: 6 }, { x: 1, z: 0, top: 5, north: 3 }, { x: 3, z: 0, top: 5, north: 1 }, { x: 1, z: 3, top: 5, north: 6 }] } },
  { id: 'B23', chapter: 7, seed: 44, size: 4, values: [5], norm: 11, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['1,0,W', '0,0,S', '1,2,E', '0,2,E', '0,1,S', '0,2,S', '3,0,S', '2,2,E'], layout: { start: { x: 2, z: 3 }, dice: [{ x: 3, z: 0, top: 4, north: 5 }, { x: 3, z: 1, top: 5, north: 1 }, { x: 2, z: 1, top: 5, north: 3 }, { x: 3, z: 2, top: 5, north: 4 }, { x: 1, z: 1, top: 5, north: 6 }, { x: 1, z: 2, top: 2, north: 1 }, { x: 1, z: 0, top: 3, north: 2 }, { x: 1, z: 3, top: 5, north: 6 }, { x: 2, z: 3, top: 5, north: 4 }, { x: 0, z: 2, top: 4, north: 6 }, { x: 0, z: 3, top: 5, north: 3 }] } },
  { id: 'B01', chapter: 5, seed: 435, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonThrees', arrow: 'N', par: 1, exact: true, solution: ['1,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 2, z: 2, top: 3, north: 2 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 1, z: 2, top: 5, north: 4 }] } },
  { id: 'B01', chapter: 5, seed: 927, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonThrees', arrow: 'N', par: 1, exact: true, solution: ['1,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 2, z: 1, top: 3, north: 2 }, { x: 2, z: 2, top: 3, north: 1 }, { x: 1, z: 2, top: 5, north: 4 }] } },
  { id: 'B02', chapter: 5, seed: 21, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonStep', par: 2, exact: true, solution: ['1,2,E', '2,2,N'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 1, z: 0, top: 3, north: 2 }, { x: 1, z: 1, top: 3, north: 2 }, { x: 1, z: 2, top: 5, north: 4 }] } },
  { id: 'B02', chapter: 5, seed: 23, size: 3, values: [3], norm: 3, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonStep', par: 3, exact: true, solution: ['1,0,S', '1,1,S', '1,2,W'], layout: { start: { x: 0, z: 1 }, dice: [{ x: 0, z: 0, top: 3, north: 5 }, { x: 0, z: 1, top: 3, north: 5 }, { x: 1, z: 0, top: 6, north: 5 }] } },
  { id: 'B03', chapter: 5, seed: 10002, size: 3, values: [3], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonLink', par: 2, exact: true, solution: ['2,0,W', '2,2,W'], layout: { start: { x: 2, z: 2 }, dice: [{ x: 2, z: 0, top: 2, north: 6 }, { x: 1, z: 1, top: 3, north: 1 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 2, z: 2, top: 2, north: 6 }] } },
  { id: 'B03', chapter: 5, seed: 10004, size: 3, values: [3], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonLink', par: 2, exact: true, solution: ['2,1,S', '1,1,E'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 1, z: 1, top: 5, north: 6 }, { x: 2, z: 1, top: 6, north: 3 }, { x: 0, z: 2, top: 3, north: 1 }, { x: 1, z: 2, top: 3, north: 5 }] } },
  { id: 'B04', chapter: 5, seed: 239, size: 3, values: [3], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonSeven', par: 4, exact: true, solution: ['1,1,E', '2,1,S', '0,1,E', '2,2,N'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 1, z: 2, top: 3, north: 5 }, { x: 0, z: 2, top: 3, north: 5 }, { x: 1, z: 1, top: 5, north: 6 }, { x: 0, z: 1, top: 6, north: 2 }] } },
  { id: 'B04', chapter: 5, seed: 755, size: 3, values: [3], norm: 4, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonSeven', par: 4, exact: true, solution: ['1,2,W', '0,2,N', '0,1,E', '2,2,W'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 2, z: 2, top: 6, north: 5 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 2, z: 0, top: 3, north: 2 }, { x: 1, z: 2, top: 3, north: 6 }] } },
  { id: 'B05', chapter: 5, seed: 10730, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,0,S', '0,0,E', '0,1,N', '3,1,W'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 0, z: 0, top: 5, north: 6 }, { x: 1, z: 0, top: 2, north: 3 }, { x: 2, z: 0, top: 3, north: 2 }, { x: 3, z: 0, top: 3, north: 6 }, { x: 0, z: 1, top: 5, north: 4 }, { x: 3, z: 1, top: 5, north: 1 }] } },
  { id: 'B05', chapter: 5, seed: 10066, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['0,0,E', '0,2,E', '0,3,N', '1,3,W'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 0, top: 6, north: 2 }, { x: 0, z: 1, top: 3, north: 5 }, { x: 1, z: 1, top: 3, north: 5 }, { x: 0, z: 2, top: 6, north: 2 }, { x: 0, z: 3, top: 2, north: 4 }, { x: 1, z: 3, top: 6, north: 5 }] } },
  { id: 'B06', chapter: 5, seed: 10099, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['3,0,S', '2,0,E', '2,1,N', '1,1,E', '1,0,S', '0,1,E'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 1, z: 0, top: 2, north: 3 }, { x: 2, z: 0, top: 6, north: 2 }, { x: 3, z: 0, top: 2, north: 3 }, { x: 0, z: 1, top: 5, north: 6 }, { x: 1, z: 1, top: 6, north: 2 }, { x: 2, z: 1, top: 2, north: 4 }] } },
  { id: 'B06', chapter: 5, seed: 10023, size: 4, values: [3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['0,1,E', '2,2,E', '2,3,W', '1,2,E', '3,3,W', '1,3,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 0, z: 1, top: 2, north: 1 }, { x: 0, z: 2, top: 3, north: 1 }, { x: 1, z: 2, top: 5, north: 6 }, { x: 2, z: 2, top: 5, north: 6 }, { x: 2, z: 3, top: 6, north: 4 }, { x: 3, z: 3, top: 6, north: 5 }] } },
  { id: 'B07', chapter: 5, seed: 10031, size: 3, values: [3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 7, exact: true, solution: ['1,1,W', '1,0,S', '1,2,W', '1,1,S', '0,0,S', '0,1,S', '2,0,S'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 0, top: 4, north: 5 }, { x: 1, z: 0, top: 4, north: 6 }, { x: 2, z: 0, top: 6, north: 3 }, { x: 1, z: 1, top: 6, north: 5 }, { x: 2, z: 1, top: 3, north: 1 }, { x: 1, z: 2, top: 5, north: 1 }, { x: 2, z: 2, top: 3, north: 1 }] } },
  { id: 'B07', chapter: 5, seed: 10079, size: 3, values: [3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['0,1,S', '2,1,W', '2,0,S', '1,1,W', '1,0,S', '0,0,E'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 0, top: 5, north: 6 }, { x: 1, z: 0, top: 5, north: 3 }, { x: 2, z: 0, top: 6, north: 3 }, { x: 0, z: 1, top: 6, north: 3 }, { x: 2, z: 1, top: 4, north: 1 }, { x: 1, z: 2, top: 3, north: 6 }, { x: 2, z: 2, top: 3, north: 1 }] } },
  { id: 'B08', chapter: 5, seed: 143, size: 4, values: [3], norm: 9, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 7, exact: true, solution: ['1,1,W', '1,0,S', '1,2,S', '1,1,S', '2,1,W', '1,1,N', '0,1,E'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 0, z: 0, top: 3, north: 2 }, { x: 1, z: 0, top: 4, north: 1 }, { x: 2, z: 0, top: 3, north: 1 }, { x: 1, z: 1, top: 3, north: 1 }, { x: 1, z: 2, top: 5, north: 3 }, { x: 2, z: 2, top: 3, north: 1 }, { x: 2, z: 3, top: 3, north: 6 }, { x: 2, z: 1, top: 6, north: 4 }, { x: 3, z: 0, top: 3, north: 6 }] } },
  { id: 'B08', chapter: 5, seed: 80, size: 4, values: [3], norm: 9, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [3], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['2,2,S', '2,3,W', '1,2,W', '0,1,S', '0,2,E', '1,0,E', '1,2,N', '1,1,N'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 0, z: 1, top: 2, north: 6 }, { x: 1, z: 1, top: 3, north: 6 }, { x: 0, z: 0, top: 3, north: 2 }, { x: 0, z: 2, top: 3, north: 1 }, { x: 0, z: 3, top: 3, north: 5 }, { x: 1, z: 0, top: 6, north: 2 }, { x: 1, z: 2, top: 6, north: 5 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 2, z: 2, top: 2, north: 6 }] } },
  { id: 'B09', chapter: 6, seed: 10155, size: 3, values: [2, 3], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonTwos', par: 3, exact: true, solution: ['0,0,S', '1,0,E', '0,1,S'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 0, z: 0, top: 5, north: 6 }, { x: 1, z: 0, top: 6, north: 2 }, { x: 1, z: 1, top: 3, north: 6 }, { x: 2, z: 1, top: 3, north: 2 }, { x: 1, z: 2, top: 2, north: 1 }] } },
  { id: 'B10', chapter: 6, seed: 10120, size: 3, values: [2, 3], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 5, exact: true, solution: ['1,2,E', '1,1,S', '1,2,W', '0,2,N', '0,1,E'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 0, top: 2, north: 1 }, { x: 2, z: 0, top: 3, north: 1 }, { x: 1, z: 1, top: 4, north: 2 }, { x: 2, z: 1, top: 3, north: 6 }, { x: 1, z: 2, top: 6, north: 2 }] } },
  { id: 'B10', chapter: 6, seed: 10318, size: 3, values: [2, 3], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,1,S', '1,2,W', '2,0,S', '2,1,W'], layout: { start: { x: 2, z: 0 }, dice: [{ x: 0, z: 0, top: 3, north: 2 }, { x: 1, z: 0, top: 3, north: 2 }, { x: 2, z: 0, top: 6, north: 5 }, { x: 0, z: 1, top: 2, north: 1 }, { x: 1, z: 1, top: 6, north: 3 }] } },
  { id: 'B11', chapter: 6, seed: 365, size: 4, values: [2, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonGlass', par: 4, exact: true, solution: ['1,2,E', '2,2,N', '3,1,N', '3,0,W'], layout: { start: { x: 1, z: 1 }, dice: [{ x: 2, z: 0, top: 3, north: 6 }, { x: 3, z: 0, top: 3, north: 6 }, { x: 1, z: 0, top: 2, north: 3 }, { x: 1, z: 1, top: 3, north: 6 }, { x: 3, z: 1, top: 4, north: 6 }, { x: 1, z: 2, top: 2, north: 4 }] } },
  { id: 'B11', chapter: 6, seed: 10055, size: 4, values: [2, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonGlass', par: 4, exact: true, solution: ['3,3,N', '3,2,W', '0,2,S', '1,1,S'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 1, z: 1, top: 6, north: 3 }, { x: 0, z: 2, top: 6, north: 3 }, { x: 1, z: 2, top: 2, north: 6 }, { x: 1, z: 3, top: 3, north: 5 }, { x: 2, z: 3, top: 3, north: 6 }, { x: 3, z: 3, top: 4, north: 6 }] } },
  { id: 'B12', chapter: 6, seed: 10932, size: 4, values: [2, 3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['1,1,N', '2,1,W', '1,1,S', '0,3,E', '0,2,S', '1,2,W'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 0, z: 0, top: 3, north: 2 }, { x: 2, z: 0, top: 2, north: 6 }, { x: 0, z: 1, top: 3, north: 5 }, { x: 1, z: 1, top: 6, north: 5 }, { x: 2, z: 1, top: 4, north: 5 }, { x: 0, z: 2, top: 5, north: 3 }, { x: 0, z: 3, top: 2, north: 1 }] } },
  { id: 'B12', chapter: 6, seed: 89, size: 4, values: [2, 3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['2,0,S', '3,0,W', '3,2,S', '3,3,W', '1,2,S', '2,2,W'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 3, z: 2, top: 4, north: 6 }, { x: 2, z: 2, top: 3, north: 1 }, { x: 3, z: 1, top: 2, north: 3 }, { x: 1, z: 2, top: 4, north: 2 }, { x: 0, z: 2, top: 2, north: 1 }, { x: 3, z: 0, top: 4, north: 6 }, { x: 2, z: 0, top: 6, north: 2 }] } },
  { id: 'B13', chapter: 6, seed: 68, size: 4, values: [2, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonFloor', par: 5, exact: true, solution: ['3,1,W', '3,2,N,p', '0,2,N,p', '2,2,N,p', '2,1,W,p'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 2, z: 0, top: 2, north: 6 }, { x: 3, z: 2, top: 2, north: 4 }, { x: 0, z: 2, top: 3, north: 2 }, { x: 3, z: 1, top: 3, north: 1 }, { x: 0, z: 0, top: 3, north: 1 }, { x: 2, z: 2, top: 3, north: 5 }] } },
  { id: 'B13', chapter: 6, seed: 342, size: 4, values: [2, 3], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, lesson: 'lessonFloor', par: 5, exact: true, solution: ['3,0,S', '0,3,E', '1,3,N', '2,3,W', '1,3,W'], layout: { start: { x: 3, z: 0 }, dice: [{ x: 3, z: 0, top: 2, north: 3 }, { x: 0, z: 3, top: 4, north: 5 }, { x: 0, z: 2, top: 2, north: 1 }, { x: 2, z: 0, top: 3, north: 5 }, { x: 2, z: 3, top: 5, north: 6 }, { x: 2, z: 1, top: 3, north: 6 }] } },
  { id: 'B14', chapter: 6, seed: 10197, size: 3, values: [2, 3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 7, exact: true, solution: ['0,1,N', '1,1,W', '1,0,S', '2,0,W', '2,1,N', '1,2,W', '2,2,W'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 1, z: 0, top: 2, north: 3 }, { x: 2, z: 0, top: 5, north: 1 }, { x: 0, z: 1, top: 6, north: 4 }, { x: 1, z: 1, top: 6, north: 5 }, { x: 2, z: 1, top: 2, north: 4 }, { x: 1, z: 2, top: 5, north: 1 }, { x: 2, z: 2, top: 6, north: 5 }] } },
  { id: 'B14', chapter: 6, seed: 83, size: 3, values: [2, 3], norm: 7, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 7, exact: true, solution: ['2,1,S', '1,1,E', '1,0,S', '0,1,E', '1,1,N', '1,2,N', '2,2,W'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 1, top: 3, north: 6 }, { x: 1, z: 0, top: 4, north: 2 }, { x: 2, z: 1, top: 6, north: 3 }, { x: 0, z: 1, top: 3, north: 5 }, { x: 0, z: 2, top: 2, north: 4 }, { x: 0, z: 0, top: 2, north: 6 }, { x: 1, z: 2, top: 6, north: 5 }] } },
  { id: 'B15', chapter: 6, seed: 10037, size: 5, values: [2, 3], norm: 9, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['4,4,N', '2,1,E', '2,0,S', '2,4,E', '3,2,E', '4,3,S', '3,3,E', '3,0,E'], layout: { start: { x: 4, z: 4 }, dice: [{ x: 2, z: 0, top: 6, north: 2 }, { x: 3, z: 0, top: 5, north: 6 }, { x: 2, z: 1, top: 6, north: 4 }, { x: 4, z: 1, top: 3, north: 2 }, { x: 2, z: 2, top: 2, north: 4 }, { x: 3, z: 2, top: 5, north: 6 }, { x: 3, z: 3, top: 6, north: 2 }, { x: 2, z: 4, top: 6, north: 4 }, { x: 4, z: 4, top: 2, north: 6 }] } },
  { id: 'B15', chapter: 6, seed: 10138, size: 5, values: [2, 3], norm: 9, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 7, exact: true, solution: ['1,1,S', '2,2,E', '3,2,S', '2,4,W', '4,3,S,p', '3,4,W', '4,4,N'], layout: { start: { x: 0, z: 2 }, dice: [{ x: 0, z: 1, top: 3, north: 6 }, { x: 1, z: 1, top: 2, north: 3 }, { x: 0, z: 2, top: 3, north: 6 }, { x: 2, z: 2, top: 4, north: 2 }, { x: 1, z: 3, top: 3, north: 1 }, { x: 4, z: 3, top: 4, north: 5 }, { x: 0, z: 4, top: 2, north: 6 }, { x: 2, z: 4, top: 3, north: 1 }, { x: 3, z: 4, top: 4, north: 6 }] } },
  { id: 'B16', chapter: 6, seed: 10014, size: 4, values: [2, 3], norm: 10, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['3,1,W', '3,2,N', '2,2,E', '3,0,W', '1,2,E', '0,1,N', '1,3,N', '1,2,N'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 1, z: 0, top: 2, north: 1 }, { x: 3, z: 0, top: 3, north: 1 }, { x: 0, z: 1, top: 3, north: 5 }, { x: 3, z: 1, top: 4, north: 6 }, { x: 1, z: 2, top: 4, north: 1 }, { x: 2, z: 2, top: 5, north: 6 }, { x: 3, z: 2, top: 4, north: 5 }, { x: 1, z: 3, top: 5, north: 3 }, { x: 2, z: 3, top: 3, north: 2 }, { x: 3, z: 3, top: 3, north: 2 }] } },
  { id: 'B16', chapter: 6, seed: 32, size: 4, values: [2, 3], norm: 10, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [2, 3], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['3,0,W', '3,1,N', '0,0,E', '1,2,S', '1,3,E', '3,2,W', '2,2,W', '1,1,S'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 0, top: 2, north: 6 }, { x: 3, z: 3, top: 2, north: 6 }, { x: 0, z: 0, top: 3, north: 6 }, { x: 3, z: 2, top: 5, north: 6 }, { x: 3, z: 1, top: 4, north: 5 }, { x: 0, z: 2, top: 2, north: 6 }, { x: 1, z: 2, top: 6, north: 4 }, { x: 1, z: 1, top: 3, north: 2 }, { x: 2, z: 1, top: 2, north: 1 }, { x: 3, z: 0, top: 6, north: 3 }] } },
  { id: 'B17', chapter: 7, seed: 13, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, lesson: 'lessonFives', par: 2, exact: true, solution: ['1,2,N', '1,1,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 3, z: 2, top: 5, north: 6 }, { x: 2, z: 2, top: 5, north: 4 }, { x: 2, z: 1, top: 5, north: 3 }, { x: 2, z: 0, top: 5, north: 1 }, { x: 1, z: 2, top: 2, north: 1 }] } },
  { id: 'B17', chapter: 7, seed: 14, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, lesson: 'lessonFives', par: 1, exact: true, solution: ['0,0,S'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 1, z: 1, top: 5, north: 1 }, { x: 1, z: 0, top: 5, north: 1 }, { x: 2, z: 1, top: 5, north: 4 }, { x: 2, z: 2, top: 5, north: 4 }, { x: 0, z: 0, top: 6, north: 5 }] } },
  { id: 'B18', chapter: 7, seed: 9, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,2,E', '2,2,N', '2,1,W', '1,1,S'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 0, z: 3, top: 5, north: 1 }, { x: 1, z: 3, top: 5, north: 3 }, { x: 0, z: 2, top: 5, north: 3 }, { x: 1, z: 2, top: 4, north: 6 }, { x: 0, z: 1, top: 5, north: 3 }] } },
  { id: 'B18', chapter: 7, seed: 13, size: 4, values: [5], norm: 5, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,2,E', '2,2,N', '2,1,W', '1,1,S'], layout: { start: { x: 1, z: 3 }, dice: [{ x: 0, z: 3, top: 5, north: 6 }, { x: 0, z: 2, top: 5, north: 6 }, { x: 1, z: 3, top: 5, north: 1 }, { x: 1, z: 2, top: 3, north: 1 }, { x: 0, z: 1, top: 5, north: 1 }] } },
  { id: 'B19', chapter: 7, seed: 213, size: 4, values: [5], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['2,3,N', '2,2,N', '1,3,W', '1,2,N'], layout: { start: { x: 1, z: 2 }, dice: [{ x: 1, z: 3, top: 4, north: 1 }, { x: 1, z: 2, top: 3, north: 2 }, { x: 0, z: 2, top: 5, north: 1 }, { x: 1, z: 1, top: 5, north: 6 }, { x: 0, z: 1, top: 5, north: 1 }, { x: 2, z: 3, top: 2, north: 1 }] } },
  { id: 'B19', chapter: 7, seed: 239, size: 4, values: [5], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 4, exact: true, solution: ['1,0,W', '0,0,S', '0,1,E', '2,0,S'], layout: { start: { x: 1, z: 0 }, dice: [{ x: 2, z: 2, top: 5, north: 3 }, { x: 2, z: 1, top: 5, north: 1 }, { x: 3, z: 2, top: 5, north: 4 }, { x: 2, z: 0, top: 6, north: 5 }, { x: 1, z: 0, top: 5, north: 3 }, { x: 3, z: 1, top: 5, north: 6 }] } },
  { id: 'B20', chapter: 7, seed: 10186, size: 5, values: [5], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['4,2,S', '4,3,W', '3,3,W', '2,3,N', '2,1,W', '1,1,S'], layout: { start: { x: 4, z: 2 }, dice: [{ x: 0, z: 1, top: 5, north: 6 }, { x: 2, z: 1, top: 3, north: 5 }, { x: 0, z: 2, top: 5, north: 3 }, { x: 4, z: 2, top: 5, north: 4 }, { x: 0, z: 3, top: 5, north: 1 }, { x: 1, z: 3, top: 5, north: 3 }] } },
  { id: 'B20', chapter: 7, seed: 10076, size: 5, values: [5], norm: 6, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['2,1,E', '3,1,S', '3,2,W', '2,2,S', '2,3,W', '0,2,E'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 1, top: 4, north: 2 }, { x: 0, z: 2, top: 4, north: 6 }, { x: 0, z: 4, top: 5, north: 3 }, { x: 1, z: 4, top: 5, north: 4 }, { x: 2, z: 4, top: 5, north: 4 }, { x: 3, z: 4, top: 5, north: 1 }] } },
  { id: 'B21', chapter: 7, seed: 146, size: 4, values: [5], norm: 8, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 6, exact: true, solution: ['1,1,W', '1,2,N', '3,3,N', '3,2,W', '2,2,W', '0,1,E'], layout: { start: { x: 2, z: 3 }, dice: [{ x: 2, z: 3, top: 5, north: 6 }, { x: 3, z: 3, top: 3, north: 5 }, { x: 1, z: 3, top: 5, north: 3 }, { x: 1, z: 2, top: 3, north: 2 }, { x: 0, z: 2, top: 5, north: 3 }, { x: 1, z: 1, top: 5, north: 1 }, { x: 1, z: 0, top: 5, north: 4 }, { x: 0, z: 3, top: 5, north: 4 }] } },
  { id: 'B21', chapter: 7, seed: 58, size: 4, values: [5], norm: 8, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 7, exact: true, solution: ['0,3,N', '1,3,W', '3,3,W', '2,3,W', '0,2,S', '2,1,S,p', '2,2,N'], layout: { start: { x: 3, z: 3 }, dice: [{ x: 3, z: 2, top: 5, north: 6 }, { x: 3, z: 3, top: 2, north: 1 }, { x: 2, z: 2, top: 5, north: 4 }, { x: 3, z: 1, top: 5, north: 6 }, { x: 1, z: 2, top: 5, north: 3 }, { x: 1, z: 3, top: 3, north: 6 }, { x: 0, z: 3, top: 5, north: 4 }, { x: 2, z: 1, top: 6, north: 2 }] } },
  { id: 'B22', chapter: 7, seed: 10010, size: 5, values: [5], norm: 10, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['0,2,E', '1,2,E', '2,2,E', '2,3,S', '1,4,N', '0,4,E', '0,3,S', '4,1,S'], layout: { start: { x: 1, z: 4 }, dice: [{ x: 4, z: 1, top: 3, north: 5 }, { x: 0, z: 2, top: 4, north: 1 }, { x: 0, z: 3, top: 3, north: 5 }, { x: 2, z: 3, top: 4, north: 5 }, { x: 3, z: 3, top: 5, north: 4 }, { x: 4, z: 3, top: 5, north: 4 }, { x: 0, z: 4, top: 6, north: 3 }, { x: 1, z: 4, top: 6, north: 2 }, { x: 3, z: 4, top: 5, north: 3 }, { x: 4, z: 4, top: 5, north: 3 }] } },
  { id: 'B22', chapter: 7, seed: 10025, size: 5, values: [5], norm: 10, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 8, exact: true, solution: ['3,4,W', '2,3,N', '3,3,S', '0,3,E', '1,3,N', '0,0,S', '0,1,S', '1,0,S'], layout: { start: { x: 3, z: 4 }, dice: [{ x: 0, z: 0, top: 2, north: 4 }, { x: 1, z: 0, top: 4, north: 5 }, { x: 3, z: 2, top: 5, north: 6 }, { x: 4, z: 2, top: 5, north: 1 }, { x: 0, z: 3, top: 6, north: 2 }, { x: 2, z: 3, top: 6, north: 2 }, { x: 3, z: 3, top: 4, north: 5 }, { x: 4, z: 3, top: 5, north: 4 }, { x: 3, z: 4, top: 4, north: 1 }, { x: 4, z: 4, top: 5, north: 6 }] } },
  { id: 'B23', chapter: 7, seed: 11, size: 4, values: [5], norm: 11, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 9, exact: true, solution: ['1,1,S', '2,1,W', '3,1,W', '2,1,S', '1,1,E', '1,0,S', '2,2,S', '3,2,W', '1,2,E'], layout: { start: { x: 2, z: 1 }, dice: [{ x: 2, z: 0, top: 5, north: 4 }, { x: 1, z: 0, top: 3, north: 5 }, { x: 1, z: 1, top: 4, north: 6 }, { x: 0, z: 0, top: 5, north: 3 }, { x: 0, z: 1, top: 5, north: 6 }, { x: 3, z: 0, top: 5, north: 3 }, { x: 2, z: 1, top: 5, north: 6 }, { x: 3, z: 1, top: 4, north: 6 }, { x: 3, z: 2, top: 4, north: 1 }, { x: 0, z: 2, top: 5, north: 1 }, { x: 3, z: 3, top: 5, north: 6 }] } },
  { id: 'B23', chapter: 7, seed: 10033, size: 4, values: [5], norm: 11, arrival: 'none', goal: { kind: 'clear' }, moves: 0, faces: [5], sinkMoves: 2, liftMoves: 1, par: 9, exact: true, solution: ['1,0,W', '0,0,S', '3,1,S', '3,0,S', '1,2,W', '1,1,S', '1,3,W', '2,0,S', '2,1,W'], layout: { start: { x: 3, z: 1 }, dice: [{ x: 1, z: 0, top: 6, north: 5 }, { x: 2, z: 0, top: 6, north: 4 }, { x: 3, z: 0, top: 6, north: 5 }, { x: 1, z: 1, top: 3, north: 5 }, { x: 2, z: 1, top: 5, north: 3 }, { x: 3, z: 1, top: 3, north: 5 }, { x: 1, z: 2, top: 3, north: 6 }, { x: 2, z: 2, top: 5, north: 3 }, { x: 1, z: 3, top: 6, north: 4 }, { x: 2, z: 3, top: 5, north: 4 }, { x: 3, z: 3, top: 5, north: 6 }] } },
];
