import type { PuzzleLayout } from '../rules';

/** What a level is about; levels of a tier stand together in the list of levels. */
export type PuzzleTier = 'intro' | 'path' | 'decoy' | 'pair' | 'big' | 'tight' | 'hard';

export interface PuzzleLevel extends PuzzleLayout {
  /** Code of the level. Progress and statistics are kept under it. */
  id: string;
  tier: PuzzleTier;
  /** Fewest rolls that clear the board, found by exhaustive search. */
  par: number;
  /** One shortest solution: cell and direction of every roll, as "x,z,D". */
  solution: readonly string[];
}

/**
 * Playtest set. The levels were laid out by a throwaway generator and solved by exhaustive
 * search; levels.test.ts replays every solution on the real rules.
 */
export const PUZZLE_LEVELS: readonly PuzzleLevel[] = [
  {
    id: '31wp6d6w',
    tier: 'intro',
    size: 3,
    dice: [
      { x: 1, z: 0, top: 3, north: 2 },
      { x: 0, z: 1, top: 2, north: 1 },
    ],
    start: { x: 1, z: 0 },
    par: 1,
    solution: ['1,0,S'],
  },
  {
    id: '300rhf8l',
    tier: 'intro',
    size: 3,
    dice: [
      { x: 0, z: 0, top: 2, north: 3 },
      { x: 2, z: 0, top: 3, north: 1 },
      { x: 1, z: 1, top: 2, north: 3 },
    ],
    start: { x: 2, z: 0 },
    par: 1,
    solution: ['2,0,W'],
  },
  {
    id: '41gym584',
    tier: 'intro',
    size: 4,
    dice: [
      { x: 3, z: 1, top: 6, north: 3 },
      { x: 2, z: 2, top: 1, north: 3 },
      { x: 3, z: 3, top: 3, north: 1 },
    ],
    start: { x: 3, z: 1 },
    par: 2,
    solution: ['3,1,S', '2,2,S'],
  },
  {
    id: '3137th4l',
    tier: 'intro',
    size: 3,
    dice: [
      { x: 0, z: 1, top: 3, north: 2 },
      { x: 2, z: 1, top: 1, north: 3 },
      { x: 0, z: 2, top: 3, north: 6 },
    ],
    start: { x: 2, z: 1 },
    par: 2,
    solution: ['2,1,W', '1,1,S'],
  },
  {
    id: '51qjrv5y',
    tier: 'path',
    size: 5,
    dice: [
      { x: 0, z: 0, top: 2, north: 6 },
      { x: 2, z: 0, top: 2, north: 4 },
    ],
    start: { x: 2, z: 0 },
    par: 3,
    solution: ['2,0,S', '2,1,W', '1,1,N'],
  },
  {
    id: '41asj9q7',
    tier: 'path',
    size: 4,
    dice: [
      { x: 1, z: 0, top: 2, north: 6 },
      { x: 1, z: 2, top: 2, north: 1 },
    ],
    start: { x: 1, z: 0 },
    par: 3,
    solution: ['1,0,E', '2,0,S', '2,1,W'],
  },
  {
    id: '303eibsl',
    tier: 'path',
    size: 3,
    dice: [
      { x: 2, z: 1, top: 3, north: 1 },
      { x: 1, z: 2, top: 1, north: 2 },
      { x: 2, z: 2, top: 3, north: 1 },
    ],
    start: { x: 1, z: 2 },
    par: 4,
    solution: ['1,2,W', '0,2,N', '0,1,E', '1,1,S'],
  },
  {
    id: '31nnznsa',
    tier: 'path',
    size: 3,
    dice: [
      { x: 1, z: 1, top: 5, north: 4 },
      { x: 0, z: 2, top: 2, north: 3 },
    ],
    start: { x: 1, z: 1 },
    par: 5,
    solution: ['1,1,N', '1,0,E', '2,0,S', '2,1,W', '1,1,W'],
  },
  {
    id: '40idabzn',
    tier: 'decoy',
    size: 4,
    dice: [
      { x: 2, z: 2, top: 5, north: 6 },
      { x: 3, z: 2, top: 2, north: 3 },
      { x: 2, z: 3, top: 3, north: 6 },
    ],
    start: { x: 3, z: 2 },
    par: 2,
    solution: ['3,2,S', '2,2,E'],
  },
  {
    id: '304k0rvh',
    tier: 'decoy',
    size: 3,
    dice: [
      { x: 2, z: 1, top: 6, north: 3 },
      { x: 0, z: 2, top: 1, north: 5 },
      { x: 1, z: 2, top: 3, north: 5 },
    ],
    start: { x: 2, z: 1 },
    par: 3,
    solution: ['2,1,S', '0,2,N', '0,1,E'],
  },
  {
    id: '305f2sbm',
    tier: 'decoy',
    size: 3,
    dice: [
      { x: 2, z: 0, top: 2, north: 3 },
      { x: 1, z: 1, top: 1, north: 5 },
      { x: 1, z: 2, top: 1, north: 5 },
    ],
    start: { x: 1, z: 1 },
    par: 4,
    solution: ['1,1,E', '2,0,W', '1,0,S', '1,2,E'],
  },
  {
    id: '400cxvgr',
    tier: 'decoy',
    size: 4,
    dice: [
      { x: 2, z: 0, top: 2, north: 4 },
      { x: 1, z: 1, top: 2, north: 6 },
      { x: 2, z: 2, top: 4, north: 6 },
    ],
    start: { x: 1, z: 1 },
    par: 5,
    solution: ['1,1,S', '2,2,N', '2,1,W', '1,2,E', '2,2,N'],
  },
  {
    id: '616y38ls',
    tier: 'pair',
    size: 6,
    dice: [
      { x: 3, z: 0, top: 1, north: 2 },
      { x: 2, z: 1, top: 3, north: 5 },
      { x: 3, z: 1, top: 3, north: 1 },
      { x: 1, z: 2, top: 3, north: 5 },
      { x: 2, z: 2, top: 6, north: 3 },
    ],
    start: { x: 1, z: 2 },
    par: 3,
    solution: ['1,2,N', '3,0,W', '2,2,W'],
  },
  {
    id: '50sw4tb0',
    tier: 'pair',
    size: 5,
    dice: [
      { x: 0, z: 1, top: 3, north: 6 },
      { x: 0, z: 2, top: 3, north: 6 },
      { x: 2, z: 2, top: 4, north: 6 },
      { x: 1, z: 3, top: 2, north: 1 },
      { x: 0, z: 4, top: 5, north: 4 },
    ],
    start: { x: 2, z: 2 },
    par: 4,
    solution: ['2,2,S', '2,3,S', '2,4,W', '0,4,N'],
  },
  {
    id: '41crex87',
    tier: 'pair',
    size: 4,
    dice: [
      { x: 0, z: 1, top: 5, north: 1 },
      { x: 2, z: 1, top: 1, north: 2 },
      { x: 3, z: 1, top: 3, north: 6 },
      { x: 2, z: 3, top: 2, north: 4 },
      { x: 3, z: 3, top: 3, north: 6 },
    ],
    start: { x: 0, z: 1 },
    par: 5,
    solution: ['0,1,S', '0,2,E', '1,2,E', '2,2,E', '2,1,S'],
  },
  {
    id: '40ls712j',
    tier: 'pair',
    size: 4,
    dice: [
      { x: 1, z: 0, top: 6, north: 2 },
      { x: 3, z: 0, top: 2, north: 3 },
      { x: 2, z: 1, top: 1, north: 3 },
      { x: 0, z: 2, top: 2, north: 3 },
    ],
    start: { x: 2, z: 1 },
    par: 5,
    solution: ['2,1,W', '1,0,W', '0,0,S', '1,1,E', '2,1,E'],
  },
  {
    id: '50hkpsjp',
    tier: 'pair',
    size: 5,
    dice: [
      { x: 0, z: 1, top: 2, north: 3 },
      { x: 1, z: 2, top: 3, north: 5 },
      { x: 2, z: 3, top: 1, north: 3 },
      { x: 4, z: 3, top: 3, north: 1 },
    ],
    start: { x: 1, z: 2 },
    par: 6,
    solution: ['1,2,E', '2,3,E', '4,3,N', '4,2,W', '2,2,W', '1,2,N'],
  },
  {
    id: '40yujrpk',
    tier: 'big',
    size: 4,
    dice: [
      { x: 1, z: 0, top: 6, north: 5 },
      { x: 2, z: 0, top: 6, north: 2 },
      { x: 1, z: 1, top: 6, north: 2 },
      { x: 2, z: 1, top: 6, north: 4 },
      { x: 1, z: 2, top: 6, north: 2 },
      { x: 1, z: 3, top: 3, north: 5 },
    ],
    start: { x: 1, z: 3 },
    par: 3,
    solution: ['1,3,W', '0,3,N', '0,2,N'],
  },
  {
    id: '41ycja0v',
    tier: 'big',
    size: 4,
    dice: [
      { x: 1, z: 0, top: 5, north: 3 },
      { x: 3, z: 0, top: 5, north: 1 },
      { x: 1, z: 1, top: 5, north: 6 },
      { x: 2, z: 1, top: 6, north: 2 },
      { x: 0, z: 3, top: 4, north: 5 },
    ],
    start: { x: 0, z: 3 },
    par: 4,
    solution: ['0,3,N', '0,2,N', '2,1,N', '0,1,N'],
  },
  {
    id: '51c3uiek',
    tier: 'big',
    size: 5,
    dice: [
      { x: 1, z: 0, top: 3, north: 1 },
      { x: 3, z: 0, top: 5, north: 6 },
      { x: 1, z: 1, top: 5, north: 1 },
      { x: 2, z: 1, top: 5, north: 6 },
      { x: 0, z: 2, top: 1, north: 2 },
      { x: 1, z: 2, top: 5, north: 4 },
      { x: 3, z: 2, top: 3, north: 6 },
    ],
    start: { x: 2, z: 1 },
    par: 5,
    solution: ['2,1,E', '3,2,W', '0,2,N', '1,0,E', '3,1,W'],
  },
  {
    id: '40za3np0',
    tier: 'big',
    size: 4,
    dice: [
      { x: 0, z: 1, top: 1, north: 4 },
      { x: 2, z: 1, top: 6, north: 4 },
      { x: 3, z: 2, top: 4, north: 6 },
      { x: 0, z: 3, top: 2, north: 3 },
      { x: 2, z: 3, top: 4, north: 2 },
      { x: 3, z: 3, top: 4, north: 1 },
    ],
    start: { x: 2, z: 1 },
    par: 6,
    solution: ['2,1,W', '0,1,S', '0,3,E', '1,3,N', '1,1,E', '2,1,S'],
  },
  {
    id: '30scaxbi',
    tier: 'tight',
    size: 3,
    dice: [
      { x: 0, z: 0, top: 3, north: 1 },
      { x: 2, z: 0, top: 3, north: 1 },
      { x: 0, z: 1, top: 1, north: 4 },
      { x: 2, z: 1, top: 2, north: 3 },
      { x: 0, z: 2, top: 3, north: 1 },
      { x: 1, z: 2, top: 3, north: 6 },
    ],
    start: { x: 0, z: 1 },
    par: 3,
    solution: ['0,1,E', '2,1,S', '1,1,N'],
  },
  {
    id: '3154c546',
    tier: 'tight',
    size: 3,
    dice: [
      { x: 0, z: 0, top: 6, north: 3 },
      { x: 2, z: 0, top: 3, north: 1 },
      { x: 1, z: 1, top: 6, north: 3 },
      { x: 2, z: 1, top: 3, north: 5 },
      { x: 0, z: 2, top: 3, north: 5 },
    ],
    start: { x: 2, z: 0 },
    par: 4,
    solution: ['2,0,W', '0,0,S', '2,1,N', '1,1,S'],
  },
  {
    id: '31laj8mm',
    tier: 'tight',
    size: 3,
    dice: [
      { x: 1, z: 0, top: 6, north: 4 },
      { x: 0, z: 1, top: 4, north: 6 },
      { x: 1, z: 1, top: 3, north: 2 },
      { x: 2, z: 1, top: 4, north: 2 },
      { x: 0, z: 2, top: 4, north: 5 },
      { x: 1, z: 2, top: 6, north: 4 },
    ],
    start: { x: 1, z: 0 },
    par: 5,
    solution: ['1,0,E', '1,2,E', '1,1,S', '2,0,W', '1,0,S'],
  },
  {
    id: '3167zpea',
    tier: 'tight',
    size: 3,
    dice: [
      { x: 1, z: 0, top: 2, north: 1 },
      { x: 2, z: 0, top: 3, north: 6 },
      { x: 0, z: 1, top: 3, north: 2 },
      { x: 0, z: 2, top: 4, north: 1 },
      { x: 2, z: 2, top: 3, north: 5 },
    ],
    start: { x: 0, z: 2 },
    par: 6,
    solution: ['0,2,E', '2,2,N', '1,0,S', '2,1,S', '0,1,S', '1,1,E'],
  },
  {
    id: '60tzjd5r',
    tier: 'hard',
    size: 6,
    dice: [
      { x: 3, z: 0, top: 4, north: 1 },
      { x: 4, z: 1, top: 6, north: 5 },
      { x: 2, z: 2, top: 3, north: 6 },
      { x: 3, z: 3, top: 2, north: 3 },
      { x: 2, z: 5, top: 3, north: 5 },
      { x: 3, z: 5, top: 3, north: 2 },
    ],
    start: { x: 3, z: 0 },
    par: 6,
    solution: ['3,0,S', '4,1,S', '4,2,W', '3,1,E', '4,1,S', '3,3,S'],
  },
  {
    id: '40kacyc0',
    tier: 'hard',
    size: 4,
    dice: [
      { x: 2, z: 1, top: 3, north: 1 },
      { x: 3, z: 1, top: 3, north: 5 },
      { x: 0, z: 2, top: 3, north: 1 },
      { x: 1, z: 2, top: 6, north: 4 },
      { x: 2, z: 3, top: 1, north: 5 },
      { x: 3, z: 3, top: 3, north: 2 },
    ],
    start: { x: 0, z: 2 },
    par: 7,
    solution: ['0,2,S', '0,3,E', '2,3,N', '1,3,E', '1,2,N', '2,2,E', '2,3,N'],
  },
  {
    id: '51ojya0w',
    tier: 'hard',
    size: 5,
    dice: [
      { x: 2, z: 0, top: 1, north: 2 },
      { x: 4, z: 1, top: 2, north: 6 },
      { x: 0, z: 2, top: 6, north: 3 },
      { x: 1, z: 2, top: 6, north: 4 },
      { x: 2, z: 2, top: 6, north: 3 },
      { x: 1, z: 3, top: 2, north: 3 },
      { x: 2, z: 3, top: 6, north: 3 },
      { x: 3, z: 4, top: 5, north: 1 },
    ],
    start: { x: 3, z: 4 },
    par: 7,
    solution: ['3,4,N', '2,2,N', '2,0,E', '3,0,S', '2,1,S', '1,3,S', '1,4,E'],
  },
  {
    id: '51bxkwmr',
    tier: 'hard',
    size: 5,
    dice: [
      { x: 4, z: 0, top: 3, north: 2 },
      { x: 2, z: 2, top: 4, north: 5 },
      { x: 3, z: 2, top: 2, north: 1 },
      { x: 4, z: 2, top: 3, north: 2 },
      { x: 1, z: 4, top: 3, north: 6 },
      { x: 3, z: 4, top: 3, north: 2 },
    ],
    start: { x: 2, z: 2 },
    par: 8,
    solution: ['2,2,S', '2,3,E', '3,3,E', '3,2,N', '3,1,E', '4,3,W', '3,3,W', '2,3,S'],
  },
  {
    id: '51uzmcdm',
    tier: 'hard',
    size: 5,
    dice: [
      { x: 0, z: 1, top: 4, north: 2 },
      { x: 4, z: 1, top: 5, north: 6 },
      { x: 0, z: 2, top: 4, north: 1 },
      { x: 3, z: 2, top: 4, north: 5 },
      { x: 0, z: 3, top: 1, north: 4 },
      { x: 2, z: 3, top: 4, north: 1 },
      { x: 3, z: 3, top: 4, north: 5 },
      { x: 1, z: 4, top: 2, north: 1 },
    ],
    start: { x: 4, z: 1 },
    par: 9,
    solution: ['4,1,S', '2,3,W', '1,3,N', '0,3,S', '1,4,N', '1,3,W', '1,2,E', '4,2,N', '4,1,W'],
  },
];
